nextstrain/nextstrain.org

- static-site/content/docs/01-getting-started/01-introduction.md
- static-site/content/docs/01-getting-started/02-quickstart.md
- static-site/content/docs/01-getting-started/03-local-vs-container-install.md
- static-site/content/docs/01-getting-started/04-local-installation.md
- static-site/content/docs/01-getting-started/05-container-installation.md
- static-site/content/docs/01-getting-started/06-windows-help.md
- static-site/content/docs/02-bioinformatics/01-introduction-to-augur.md
- static-site/content/docs/02-bioinformatics/02-what-is-a-build.md
- static-site/content/docs/02-bioinformatics/04-customizing-a-build.md
- static-site/content/docs/02-bioinformatics/05-data-formats.md
- static-site/content/docs/03-tutorials/01-zika.md
- static-site/content/docs/03-tutorials/02-tb.md
- static-site/content/docs/04-interpretation/01-auspice.md
- static-site/content/docs/05-contributing/01-philosophy.md
- static-site/content/docs/05-contributing/03-documentation.md
- static-site/content/docs/05-contributing/04-development.md
- static-site/content/docs/06-narratives/01-introduction.md
The was a mix of British and American spellings throughout. I (rather arbitrarily) moved things to be American. Mainly affecting "visualise" vs "visualize".
> Pass at spelling

- static-site/src/components/Cards/styles.jsx
- static-site/src/components/Footer/index.jsx
- static-site/src/components/splash/index.jsx
1. Add link to docs/contributing/community-builds/
2. Tweak spacers
3. Reflow text for readability
> Tweak splash page

- README.md
- static-site/README.md
These are the README-only changes from #25, separated by request from @jameshadfield .
> Readme updates

- .gitignore
- .travis.yml
- README.md
- auspice/client/navbar.js
- auspice/server/getAvailable.js
- auspice/server/getDataset.js
- auspice/server/getDatasetHelpers.js
- auspice/server/sources.js
- auspice/server/utils.js
- authn.js
- build.sh
- package-lock.json
- package.json
- server.js
- static-site/README.md
- static-site/src/components/nav-bar/index.jsx
Details in the commit messages and our ongoing Slack convos.
> Private datasets for INRB

- static-site/content/docs/01-getting-started/01-introduction.md
- static-site/content/docs/01-getting-started/02-quickstart.md
- static-site/content/docs/01-getting-started/03-local-vs-container-install.md
- static-site/content/docs/01-getting-started/04-local-installation.md
- static-site/content/docs/01-getting-started/05-container-installation.md
- static-site/content/docs/01-getting-started/06-windows-help.md
- static-site/content/docs/02-bioinformatics/01-introduction-to-augur.md
- static-site/content/docs/02-bioinformatics/02-what-is-a-build.md
- static-site/content/docs/02-bioinformatics/03-augur-commands.md
- static-site/content/docs/02-bioinformatics/04-customizing-a-build.md
- static-site/content/docs/02-bioinformatics/05-data-formats.md
- static-site/content/docs/03-tutorials/01-zika.md
- static-site/content/docs/03-tutorials/02-tb.md
- static-site/content/docs/04-interpretation/01-auspice.md
- static-site/content/docs/05-contributing/01-philosophy.md
- static-site/content/docs/05-contributing/02-community-builds.md
- static-site/content/docs/05-contributing/03-documentation.md
- static-site/content/docs/05-contributing/04-development.md
- static-site/content/docs/06-narratives/01-introduction.md
- static-site/src/components/Cards/coreCards.js
Copy edits to the nextstrain docs on nextstrain.org
> Copyedit docs

- README.md
- package-lock.json
Document the required AWS credentials for running the nextstrain.org
site locally with groups (e.g. "login") functionality.
> Document aws credentials

- static-site/content/docs/05-contributing/01-philosophy.md
- static-site/content/docs/05-contributing/02-community-builds.md
- static-site/content/docs/05-contributing/03-documentation.md
- static-site/content/docs/06-narratives/01-introduction.md
Corrections to a few grammar/spelling errors I found when reading through the docs.
> Nextstrain.org Docs Copy edit

- .eslintrc
- auspice/server/sources.js
- docs/glossary.md
- docs/groups.md
- docs/infrastructure.md
- server.js
Details in the individual commit messages. Resolves #44 and partially resolves #53.
The refactoring I did in provisioning the new `seattleflu` group is reflected in the documentation, hence why this is one PR.
> Documentation of Groups and provisioning of new Seattle Flu group

- auspice/client/languageSelector.js
- auspice/client/navbar.js
- auspice/server/getNarrative.js
- auspice/server/utils.js
- package-lock.json
- package.json
- redirects.js
- server.js
This is specifically for nCoV narratives.
1. Will try to redirect to a translated narrative if the user has a language preference set. 
2. Displays a dropdown that shows all available languages for a dated narrative. 
No styling has been done for the dropdown yet.
> Prototype auto language redirect & language selector

- static-site/content/docs/03-tutorials/01-zika.md
- static-site/content/docs/03-tutorials/02-tb.md
Fix for https://github.com/nextstrain/nextstrain.org/issues/84
> issue #84 update tutorial for Zika and TB

- server.js
bit of a hackup, but should fix the issue
fixes #123
> fix 404 issue

- static-site/content/docs/01-getting-started/04-local-installation.md
> Local install docs: s/source/conda/

- static-site/content/help/02-coronavirus/04-Technical-FAQ.md
This pull request adds some technical FAQs that we now send out as a standard reply to emails, hopefully routing enquiries more efficiently.
Nothing code-based. Just improved communication.
Just putting up a new md file. I think just verify that you are happy with the way it looks (and that it answers all the questions you think it should)
> add technical FAQs

- static-site/content/docs/02-bioinformatics/03-augur-commands.md
this is a good candidate for a whole page being replaced with a link (which I didn't do yet with this PR) - see #164 
#164
Just tested that the new link works.
> Link augur commands to augur docs

- src/sources.js
> add cog-uk nextstrain group

- package-lock.json
- package.json
- server.js
> Upgrade auspice 2.16

- package-lock.json
- package.json
- server.js
See nextstrain/auspice#1146 for rationale for these
changes. 
Depending on how gatsby is creating assets, we could improve
the cache-control for those in a future PR.
This PR sits on top of PR #176
> Improve cache control of auspice assets

- redirects.js
- static-site/content/allSARS-CoV-2Builds.yaml
- static-site/gatsby-node.js
- static-site/src/components/splash/styles.jsx
- static-site/src/pages/sars-cov-2.jsx
see https://github.com/nextstrain/nextstrain.org/issues/180
I will fill this description out with more TODOs etc but just creating the draft for now so that we have a place to iterate on the design, etc. 
Fixes #  
Related to #  
> first draft of sars-cov-2 builds page;

- package-lock.json
- package.json
> update auspice to 2.17.1

- package-lock.json
- package.json
> update auspice to 2.17.4

- src/sources.js
We now have Nextstrain Groups with buckets with over 1000 keys. The previous
implementation only returned 1000 keys from a bucket resulting in us missing some
datasets / narratives when listing the bucket, which meant they weren't displayed
on the group's splash page.
Better solutions are more than welcome, and it would be valuable to know how others would have implemented this.
Closes #186
> Add pagination for S3 listings to allow buckets with >1000 keys

- package-lock.json
- package.json
> upgrade auspice to 2.18.2

- package-lock.json
- package.json
> upgrade auspice to 2.18.3

- README.md
- package-lock.json
- package.json
See commit messages for further details
> Fix auspice scroll overlay

- .eslintrc
- README.md
- package-lock.json
- package.json
- test/smoke-test/auspice_client_requests.json
- test/smoke-test/auspice_client_requests.test.js
This commit implements smoke-testing to test requests originating from the Auspice client to the nextstrain.org server (i.e. API GET requests starting with `/charon/`).
The API calls and expected resonses are defined in ./test/smoke-test/auspice_client_requests.json and can be run via
```
npm run test:ci
```
Which will run a local server for the duration of the tests.
Alternatively, you can run your own server in the background and run `npm run smoke-test`.
Closes #217
--- 
Note that these tests are not yet run by TravisCI as it requires AWS credentials to be set in order to access Nextstrain Groups  (even public ones). Error
```
(node:10017) UnhandledPromiseRejectionWarning: CredentialsError: Missing credentials in config
at IncomingMessage.<anonymous> …
```
> Implement smoke testing

- package-lock.json
- package.json
> update auspice to v2.20.1

- static-site/content/allSARS-CoV-2Builds.yaml
update sars splash -- might be too much...
> update sars-build registry

- docs/api.md
- src/getSourceInfo.js
- test/smoke-test/auspice_client_requests.json
> add authz to getSourceInfo API & add documentation

- static-site/src/pages/sars-cov-2.jsx
would ordinarily just push live but wanted to give @emmahodcroft a chance to have eyes on it and be the one to merge in case any edits are necessary.
> sars-cov-2 page add link to Emma's variant summary

- package-lock.json
- package.json
> update auspice to v2.21

- static-site/content/allSARS-CoV-2Builds.yaml
Closes #251
All other links in the YAML checked & are working (checking done after merge of #250).
> fix links for Bosnia and Herzegovina build

- static-site/content/allSARS-CoV-2Builds.yaml
This pull request is for adding Thailand build at https://nextstrain.org/community/fai-k/coni/Thailand to the SARS-CoV-2 build list.
> Add Thailand build

- static-site/src/components/sars-cov-2/build-map.jsx
also remove the center defaults since
this seems to do nothing, no matter the
value of it. Instead I recenter the map
by adjusting maxBounds.
> build-map change bounds, include NZ in default view, move legend top right

- package-lock.json
- package.json
PR for review-app testing before merge & (automatic) deployment
> update auspice to v2.24.0

- static-site/src/components/build-pages/dataset-select.jsx
- static-site/src/components/build-pages/sit-reps.jsx
- static-site/src/pages/sars-cov-2.jsx
Instead of dropdowns, use the filterable dataset-select component.  Details in commit message.
> filterable dataset list on /sars-cov-2

- package-lock.json
- package.json
Also available at dev.nextstrain.org for testing purposes
> upgrade auspice to v2.25.1

- authn.js
> Cookie security

- docs/api.md
- src/getDataset.js
- src/getDatasetHelpers.js
- src/sources.js
- test/smoke-test/auspice_client_requests.json
These are all things I started tidying up while in the code for other purposes.
> Grab bag of cleanups to /charon/… handlers

- static-site/src/components/Datasets/sit-reps.jsx
this removes an old workaround made
obsolete by #280 and updates a comment
post- #271
> update comments and dev server address;

- LICENSE
- LICENSE.third-party
- authn.js
- package.json
- src/authn/bearer.js
- static-site/README.md
Series of related commits leading up to acceptance of `Authorization: Bearer <token>` headers for authentication. See commit messages for full details.
> authn: Accept Bearer tokens in Authorization headers

- static-site/src/layouts/generic-page.jsx
- static-site/src/sections/influenza-page.jsx
- static-site/src/sections/sars-cov-2-page.jsx
- static-site/src/sections/sequence-search-list.jsx
- static-site/src/sections/sequence-search.jsx
abstracts some commonly used header
and footer bits to reduce duplicate code
and make new pages easier.
> generic page component;

- src/getAvailable.js
- src/metaSources.js
- static-site/src/pages/groups.jsx
My attempt to solve #306 (for groups only) in a simple manner. @tsibley could you check out the first commit & how it relates to your implementation of sources. See commit messages for more details. Review App will be disabled for now.
> Collect group assets

- server.js
- src/getAvailable.js
- src/metaSources.js
- static-site/gatsby-node.js
- static-site/src/components/splash/index.jsx
- static-site/src/components/splash/userGroups.jsx
- static-site/src/pages/groups.jsx
- static-site/src/sections/influenza-page.jsx
- static-site/src/util/datasetsHelpers.js
to do:
- GH action to update static dataset listing
- detailed introduction to what groups are and links to docs
- list of all groups similar to cards on splash page
> /groups page

- package-lock.json
- package.json
> auspice 2.26.0

- auspicePaths.js
- server.js
- static-site/gatsby-node.js
- static-site/src/components/Datasets/dataset-select.jsx
- static-site/src/components/Datasets/filter-selection.jsx
- static-site/src/components/Datasets/list-datasets.jsx
- static-site/src/components/splash/groupHeading.jsx
- static-site/src/sections/individual-group-page.jsx
on top of #313. Second commit message has the details. WIP
> Gatsby handle individual groups pages

- package-lock.json
- package.json
> auspice v2.27.0

- src/sources.js
PR for visibility. Merging immediately.
> Add private group for PIGIE

- package-lock.json
- package.json
> Update Auspice to v2.28.0

- package-lock.json
- package.json
Will merge after testing using the Heroku Review App
> upgrade auspice to 2.29.1

- auspicePaths.js
- static-site/gatsby-node.js
- static-site/src/components/splash/sourceInfoHeading.jsx
- static-site/src/sections/community-repo-page.jsx
- static-site/src/sections/individual-group-page.jsx
Will add more details here soon; for now see commit messages.
> Community repo pages

- static-site/content/SARS-CoV-2-Datasets.yaml
- https://nextstrain.org/community/BryanTegomoh/Nextstrain-Builds@main/Cameroon
- https://nextstrain.org/groups/nebraska-dhhs
- https://nextstrain.org/community/BryanTegomoh/NebraskaDHHSNextStrainBuild/Nebraska/Last/Four/EpiWeeks
- https://nextstrain.org/community/josephfauver/ncovNE@main/
- https://nextstrain.org/groups/waphl/
- https://nextstrain.org/community/tgennorth/arizona-covid-19/AZ
> add builds to /sars-cov-2;

- static-site/content/SARS-CoV-2-Datasets.yaml
These narratives are not new, but I want to add them to this page
for completeness. I think the dataset table is more appropriatethan the sit-rep section below.
Tested locally
> Add two NZ narratives to /sars-cov-2 page

- package-lock.json
- package.json
Currently deployed at dev.nextstrain.org. Merging will result in deployment to nextstrain.org
> auspice v2.30.0

- static-site/content/SARS-CoV-2-Datasets.yaml
Putting this here so we can click merge if the organization links are good or edit them if necessary.
> add sarscov2 builds

- src/sources/index.js
- src/sources/models.js
Prompted by @jameshadfield's comments during review of PR #435.
> Explain the design and intent of our source model classes

- static-site/content/SARS-CoV-2-Datasets.yaml
> PR 448 + tweaks

- src/authn/index.js
Fixes a regression¹ where authz checks throw an assertion error because
authzRoles is missing on the user because many existing sessions lack
it.  This results in 500 errors for much of the web site if you have
such a session.
The user.groups array will also be updated to exclude any authz role
groups.
One downside of this approach is that the changes aren't saved back to
the session, so the existing session must be "upgraded" on the fly for
every request until the user logs out and logs back in (or the session
expires).  We could explicitly force a resave of the session when
needed, but I'm going to leave that for another commit to get a fix out
sooner.
¹ https://github.com/tsibley/blab-standup/blob/master/2022-02-23.md
---
Validated locally. Will merge and deploy once validated on …
> authn: Upgrade existing sessions which pre-date addition of authzRoles

- scripts/migrate-group
Minor changes I meant to include in the other fixups in #508. PR for visibility, like that one.
> Update migrate-groups deploy steps

- aws/iam/policy/NextstrainDotOrgServerInstanceDev.json
- scripts/migrate-group
See commits. Will merge after CI passes, as this is to hotfix CI.
https://github.com/nextstrain/private/issues/28
Tests pass locally now when I use the dev server IAM user.
> Allow dev instances to read blab group data

- package-lock.json
- package.json
Tested locally (Heroku review apps not working currently) so will merge immediately
> auspice 2.37.0

- docs/infrastructure.md
> Add clades.nextstrain.org to subdomains list

- static-site/src/sections/sars-cov-2-page.jsx
Revises text to:
- include split between 6m and all-time analyses
- include GISAID / open split
- drop strain search link
- drop contributor link (I assume anyone this interested will get there through docs)
- revise text throughout
Tested locally.
> Revise SARS-CoV-2 landing page text

- .github/workflows/ci.yml
- .github/workflows/update-dataset-listings.yml
- .github/workflows/update-search.yml
- Prevent Actions from running on forks - this is because I kept getting failures over at https://github.com/victorlin/nextstrain.org/actions
- Update other Actions usages for consistency.
_N/A_
_N/A_
> Update GitHub Actions

- package-lock.json
- package.json
Tested locally so will merge immediately and release to canary
> auspice 2.37.1

- package-lock.json
- package.json
Merging immediately to trigger release to canary
> auspice 2.37.2

- aws/iam/policy/NextstrainDotOrgServerInstance.json
- data/groups.json
Tracked as <https://github.com/nextstrain/private/issues/52>.
> Migrate inrb-drc group to multi-tenant storage

- src/authn/index.js
This context mark was broken when I moved its bit of code from
deserializeUser() into the passport.authenticate() callback for the
session strategy in "authn: Switch to custom authenticator callbacks"
(aca4d07).  It turns out the session strategy, unlike other strategies,
doesn't invoke the callback for success conditions only error
conditions.  Move the mark back into deserializeUser().
The bug manifested as automatic redirects to the canary not working
anymore, as that's the only thing that uses authnWithSession currently.
I only noticed this after a recent (unrelated) deploy.
Related to #541.
> Fix req.context.authnWithSession mark

- src/endpoints/charon/getDataset.js
Fix two bugs recently introduced to /charon/getDataset in its fallback to v1. See commit messages for details.
Related to #557.
> charon/getDataset: Fix fallback to v1

- docs/infrastructure.md
These were already documented on the internal "Third party services"
wiki page, but missing here.
_N/A_
_N/A_
> Add domain entries for docs, discussion, support

- .github/workflows/update-dataset-listings.yml
- .github/workflows/update-search.yml
This allows for more convenient manual testing, such as for #592.
_N/A_
_N/A_
> Add workflow_dispatch trigger to dataset search scripts

- .github/dependabot.yml
Adds some useful links.
_N/A_
_N/A_
> Add comments to dependabot.yml

- src/app.js
- src/sources/community.js
- static-site/src/sections/community-repo-page.jsx
- static-site/src/util/datasetsHelpers.js
- test/auspice_client_requests.json
> Narratives-only Community repos

- static-site/src/components/layout.jsx
> Add reverse link for verifying the link in our @nextstrain@mstdn.science profile

- docs/api-restful.rst
[_(preview)_](https://nextstrain--633.org.readthedocs.build/projects/nextstrain-dot-org/en/633/api-restful.html)
To reflect new features from 833ea30fa2b5b97c931a9b8d94a4560b255f34ae and 6b48bc9cf57e9cf287499d9a600ca8007099059d.
Use the broader term "group settings endpoints" to represent all endpoints under the settings/ namespace since it is expected to contain more features in the future.
Resolves #625.
_N/A_
> Add group customization endpoints to API docs

- docs/terraform.rst
Suggestions from @victorlin's post-merge review of https://github.com/nextstrain/nextstrain.org/pull/656.
> Update Terraform docs

- develop.sh
- nodemon.json
- package-lock.json
- package.json
Handy when working on server-side code.
(and maybe you can manage to convince your brain to read "nodemon" as "Node mon(itor)" and not "no demon"…)
> Use nodemon for automatic server reloading in development

- docs/api-restful.rst
- src/app.js
- src/endpoints/groups.js
- src/endpoints/index.js
- src/endpoints/options.js
- src/endpoints/sources.js
Motivated by:
https://github.com/nextstrain/nextstrain.org/pull/671#discussion_r1163207004
https://github.com/nextstrain/nextstrain.org/pull/671#discussion_r1179624832
> Generalize OPTIONS

- server.js
- src/utils/index.js
This function is used in one place, to provide a "version" that's not necessary.  Since the implementation is nonsense to begin with, just remove it.
> Remove the nonsense that is utils.getGitHash()

- src/config.js
- src/redis.js
> Redis assertions

- docs/api-restful.rst
- docs/conf.py
> docs: Intersphinx cleanups

- src/authn/index.js
Reading the OAuth 2.0 spec again¹, I noted that:
> The authorization server MAY issue a new refresh token, in which
> case the client MUST discard the old refresh token and replace it
> with the new refresh token.  The authorization server MAY revoke the
> old refresh token after issuing a new refresh token to the client.
I had assumed the refresh token itself was never renewed as I never observed AWS Cognito doing so in practice, but the spec is clear here and we want to support a wider variety of IdPs.  Renewable refresh tokens would actually be welcome in Cognito as then we could limit their lifetime to be much closer to the max session age we set.  Or perhaps Cognito does renew them, but only as necessary and we've never happened to notice this issue!
¹ …
> authn: Update the refresh token when renewing tokens, if applicable

- docs/api-restful.rst
- docs/index.rst
- docs/production.rst
Motivated by our work with CDC for them to be able to internally host nextstrain.org, but this documentation will also be useful for ourselves.
We can adapt/amend it later to account for any "Nextstrain Groups Server" (i.e. just the Groups bits of nextstrain.org) that we end up creating.
Related-to: <https://github.com/nextstrain/private/issues/94>
> docs: Production requirements

- docs/Makefile
- docs/api-restful.rst
- docs/index.rst
- docs/infrastructure.md
- docs/production.rst
- env/outputs.tf
- env/production/config.json
- env/production/outputs-extra.tf
- env/testing/config.json
- package-lock.json
- package.json
- src/authn/index.js
- src/aws.js
- src/cognito.js
- src/config.js
- src/endpoints/charon/setAvailableDatasets.js
- src/s3.js
- src/sources/groups.js
- test/authn.test.js
- test/s3.test.js
Add configurability for various constants, motivated by our [work with CDC](https://github.com/nextstrain/private/issues/94). See commits for details.
> Configurability

- .github/dependabot.yml
This reflects changes in GiHub's evolving UI.
> Update manual dependabot invocation steps

- src/redirects.js
- static-site/src/components/splash/index.jsx
Went through `src/redirects.js` and addressed things that I found were out of date.
N/A
> Check redirects

- static-site/data/SiteConfig.js
- static-site/gatsby-config.js
- static-site/src/components/SEO/SEO.jsx
Small improvements identified while working on #735.
> static-site config cleanup

- static-site/content/community-datasets.yaml
The objective of this is to keep the scientific community updated regarding the circulating SARS-CoV-2 strains in the countries part of the African and Malagasy Council of Higher Education (CAMES) for the Also-Covid-19 Project. It will be updated when needed.
Our GitHub repository is https://github.com/AlbertRockG/ncov-cames
Please, do let me know if there are any suggestions. Thanks
> Add CAMES build to Nextstrain Community build repository.

- static-site/src/components/Cards/pathogenCards.js
> Add card for lassa

- static-site/src/sections/pathogens.jsx
Keeping the text relevant.
N/A
> Update pathogens page

- static-site/content/community-datasets.yaml
Modified the dataset to include wheat blast fungus diversity in the pandemic lineage. Added the GitHub repo that contains the JSON file for Auspice.
> Update community-datasets.yaml with wheat blast fungus pandemic lineage

- .github/workflows/index-resources.yml
- resourceIndexer/constants.js
- resourceIndexer/coreStagingS3.js
See commit messages for details. I'm going to merge this without review as I think the changes are minor and they facilitate review of #803 without needing to rebuild the index locally, but review comments post merge are welcomed.
> Update s3 indexing (core + staging)

- data/manifest_core.json
Update `data/manifest_core.json` to visualize the new `genome` and `N450` trees for measles
> Update `data/manifest_core.json` with `genome` and `N450` for measles

- auspice-client/customisations/config.json
See https://github.com/nextstrain/auspice/pull/1763 for context.
> [auspice] Add link out modal

- data/manifest_core.json
See https://github.com/nextstrain/avian-flu/pull/21 for context
> [manifest] add avian-flu/h5n1-cattle-outbreak/genome

- package-lock.json
- package.json
- src/authn/index.js
- src/middleware.js
https://github.com/nextstrain/nextstrain.org/pull/839#discussion_r1579826822
> Remove old migration paths

- Procfile
- README.md
- docs/infrastructure.md
- package.json
- src/config.js
- src/fetch.js
> config: Use our own fetch() for logging and proxy (and caching) support

- static-site/src/components/ListResources/Showcase.jsx
- static-site/src/components/ListResources/index.jsx
Keeps the two references in sync.
N/A - small thing I thought of while working on these files.
> Put list anchor ID in a variable

- static-site/src/components/Footer/sitemap.yaml
Nothing else is abbreviated and we have the space, so it's nice to use the full word.  Super minor nit.
> sitemap: Docs → Documentation

- static-site/src/components/splash/index.jsx
[_preview_](https://nextstrain-s-victorlin--j4b86l.herokuapp.com/)
Small changes preparing for #901
I considered converting to TypeScript but decided against it since there's a couple hurdles and this component wouldn't benefit much from the conversion.
> Splash refactor

- static-site/.eslintrc.yaml
- static-site/data/SiteConfig.jsx
- static-site/src/components/Footer/index.jsx
- static-site/src/components/Footer/sitemap.jsx
- static-site/src/components/ListResources/index.tsx
- static-site/src/components/Sidebar/index.jsx
- static-site/src/components/nav-bar/index.jsx
- static-site/src/components/splash/index.jsx
- static-site/src/sections/community-page.jsx
- static-site/src/sections/community-repo-page.jsx
- static-site/src/sections/individual-group-page.jsx
- static-site/src/sections/pathogens.jsx
Consistently use server-side navigation links across the codebase.
> Replace Next.js Links with HTML anchor

- static-site/content/resource-listing.yaml
- static-site/src/components/splash/showcase.yaml
[_preview_](https://nextstrain-s-victorlin--abdljp.herokuapp.com)
Keeping things consistent.
- Fixes #917
> Standardize pathogen title names 

- static-site/content/blog/2024-06-12-new-resources-for-measles.md
Add author list to the measles blog post
> Add author list to measles blog post

- static-site/content/blog/2024-06-12-new-resources-for-measles.md
The link to the WHO document stopped working (it leads to a website that has the name of the document, but no longer actually has a link to the document), and so I replaced it with a link that goes directly to the document.
> Update weblink to WHO document

- docs/api-restful.rst
Replace seasonal flu with Zika in API examples based on [Slack discussion](https://bedfordlab.slack.com/archives/C03KWDET9/p1719943529502889?thread_ts=1719612970.204079&cid=C03KWDET9).
[Preview of changes to docs](https://nextstrain--941.org.readthedocs.build/projects/nextstrain-dot-org/en/941/api-restful.html#synopsis).
> Replace seasonal flu with Zika in API examples

- data/manifest_core.json
- src/routing/core.js
Adds route and manifest_core entry for `seasonal-cov` datasets.
https://github.com/nextstrain/seasonal-cov/issues/13
> Update routes for seasonal cov

- docs/api-restful.rst
Follow-up to https://github.com/nextstrain/nextstrain.org/pull/941#discussion_r1664922263
> Re-align whitespace

- docs/infrastructure.md
c.f. <https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1718744458811129?thread_ts=1718743923.841929&cid=C7SDVPBLZ>
> docs: Explicate our promotion policy

- docs/infrastructure.md
This section always seemed to leave too much unsaid to me, so I finally said it.
> docs: Explicate rollbacks, and why they're preferred, a little more

- docs/api-restful.rst
Follow-up to https://github.com/nextstrain/nextstrain.org/pull/941#discussion_r1664924025
> Use example with multi-part pathogen URLs

- env/production/config.json
- env/testing/config.json
Follow up to https://github.com/nextstrain/nextstrain.org/pull/955
Bumping the RESOURCE_INDEX version should make the transition smoother when we promote the changes to prod.
> Bump RESOURCE_INDEX version

- static-site/src/components/splash/index.tsx
Fixes styling issues noted by @tsibley [on Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1722362495986289?thread_ts=1722357213.513769&cid=C01LCTT7JNN).
> Tweak splash styles

- data/manifest_core.json
- src/routing/core.js
Add rabies to `data/manifest_core.json` and `src/routing/core.js` so tree can be viewed at `nextstrain.org/rabies`
> Add rabies

- .github/workflows/ci.yml
This reverts PR #976 
- Closes #975
> Restore resource indexer dependency in CI

- docs/conf.py
- static-site/README.md
Figured I would get these cleaned up, since I'm adding stuff with the RSS feeds that has new copyright statements. 
Per nextstrain/private#103
> Remove years from copyright statements

- docs/infrastructure.md
Copies @victorlin's [excellent instructions from Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1718405509987409?thread_ts=1718405319.885239&cid=C01LCTT7JNN) for future newbies to the process like me.
> Clarify steps to diff prior to promoting

- static-site/content/featured-analyses.yaml
> Fix community URL

- .gitignore
- build.sh
- groupsApp.md
- package-lock.json
- package.json
- scripts/generate-blog-feeds.js
- static-site/data/BaseConfig.js
- static-site/data/SiteConfig.jsx
- static-site/src/components/layout.jsx
- static-site/src/util/blogFeeds.js
- static-site/src/util/blogPosts.js
Add RSS generation script and hook it into build [#932]
Note: Atom and JSON feeds will be added to this once any review of the overall metadata is complete.
* Add function to `blogPosts.js` to read blog post and generate feed with the 10 most recent posts into the `public` directory
* Add new top-level script that calls the new `generateBlogFeeds` function
* Add package.json:scripts target to run this script
* Hook that package.json:scripts target into build.sh
* Ignore the new build-time generated file
Closes #932
> Add RSS feed [#932]

- static-site/content/blog/2024-09-03-augur-v25-features.md
Adding Augur blog post to the blog -- [preview](https://nextstrain-s-augur-v25--up2wk1.herokuapp.com/blog/2024-08-30-augur-v25-features)
Closes #1003
> Augur v25 blog post [#1003]

- README.md
- package-lock.json
- package.json
> Unpin Node.js

- static-site/content/featured-analyses.yaml
Add rabies card to main splash page
https://github.com/nextstrain/nextstrain.org/pull/1022
https://github.com/nextstrain/nextstrain.org/issues/940
> Add rabies card to main splash page

- auspice-client/package-lock.json
- auspice-client/package.json
This reverts commit 04784ba7d847de8ffe7bed72e79348f77ea2474e.
https://github.com/nextstrain/auspice/issues/1895
> Revert to auspice 2.59.1

- static-site/src/components/ListResources/useDataFetch.ts
> Fix groups resource listing

- static-site/content/blog/2024-12-10-auspice-1password-issue.md
_[preview](https://nextstrain-s-victorlin--yn32uc.herokuapp.com/blog/2024-12-10-auspice-1password-issue)_
https://github.com/nextstrain/auspice/issues/1919
> Add blog post for 1Password extension issue

- data/manifest_core.json
Add the GPC tree to the lassa display
* https://next.nextstrain.org/lassa/gpc
> Add gpc tree to lassa display

- static-site/app/blog/[id]/page.tsx
- static-site/app/blog/[id]/styles.module.css
- static-site/app/blog/parseMarkdown.ts
- static-site/app/blog/utils.ts
- static-site/app/styles/globals.css
This allows for better scoping of the style definitions.
Follow-up to https://github.com/nextstrain/nextstrain.org/pull/1091#discussion_r1881202912
> Use page-specific CSS Module for anchor styling

- static-site/content/blog/2024-12-10-auspice-1password-issue.md
Impacted users will want to know this.
Follow-up to #1088
https://github.com/nextstrain/auspice/issues/1919
> Update blog post on 1Password extension issue

- data/manifest_core.json
- test/date_descriptor.test.js
- test/inventory_parsing.test.js
PR that comes after merging the following WNV PRs
* https://github.com/nextstrain/WNV/pull/70
* https://github.com/nextstrain/WNV/pull/61
> Add global, wa, lineage-1A, and lineage-2 trees to WNV display

- data/manifest_core.json
Seasonal flu and HMPV were in the wrong places.
> Alphabetize manifest

- docs/api-restful.rst
- src/app.js
- src/endpoints/cli.js
- src/endpoints/index.js
- src/endpoints/pathogenRepos.js
- src/fetch.js
- src/routing/index.js
- src/routing/pathogenRepos.js
> Pathogen resolution endpoints

- static-site/app/pathogens/[[...pathogens]]/content.tsx
Small touch ups to the intro text.
N/A
> Adjust wording on pathogens page

- static-site/content/blog/2025-04-22-conda-runtime-out-of-sync-issue.md
- static-site/content/blog/2025-05-12-conda-runtime-*nsync.md
and update old post to mention it too.
> Add blog post about Conda runtime updates resuming

- static-site/app/contact/page.tsx
Prompted by discussion in Slack
<https://bedfordlab.slack.com/archives/CBVHPFMGX/p1747672893807899>
> contact: add `mailto` link for hello@nextstrain.org

- static-site/content/blog/2025-05-30-introducing-nextstrain-run.md
- static-site/content/blog/2025-06-13-introducing-nextstrain-run.md
Motivated by discussion in Slack.¹
¹ <https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1746725082322049>
> blog: Introducing `nextstrain run`

- static-site/content/blog/2025-07-16-snakemake-v9-update.md
- static-site/content/blog/2025-07-17-snakemake-v9-update.md
_[preview](https://nextstrain-s-blog-snake-f2tghf.herokuapp.com/blog/2025-07-16-snakemake-v9-update)_
Draft of blog post for upgrading to Snakemake v9
Resolves https://github.com/nextstrain/nextstrain.org/issues/1182
> blog: Upgrade to Snakemake v9

- static-site/content/blog/2025-09-29-standardized-multiple-inputs.md
[Preview](https://nextstrain-s-blog-stand-0aegkc.herokuapp.com/blog/2025-09-29-standardized-multiple-inputs)
Resolves https://github.com/nextstrain/nextstrain.org/issues/1231
Related to https://github.com/nextstrain/pathogen-repo-guide/pull/91
> Add blog post for standardized multiple inputs
