auspice/server/getDatasetHelpers.js
auspice/server/setAvailableDatasets.js

Previously the dataset selectors were not in the desired order due to the default value appearing first. This commit fixes this for the nextstrain.org server. Note that this functionality will be moved to the client when the new server API is implemented (see https://github.com/nextstrain/auspice/issues/687).
This commit closes Auspice issue https://github.com/nextstrain/auspice/issues/696.

Order datasets selectors

---

server.js
static-site/redirects.json
static-site/src/components/Cards/index.jsx
static-site/src/components/splash/index.jsx

It seems like it would be common to expect nextstrain.org/community to exist given that there are pages under this heading. This commit creates a redirect from `/community` to the splash page cards at `/#community`. This required adding scrollable anchor tags to the splash page.

Include redirect of /community to splash

---

README.md
auspice/client/navbar.js
auspice/server/getDataset.js
auspice/server/getNarrative.js
auspice/server/utils.js
build.sh
package-lock.json
package.json
static-site/package-lock.json

Normal deps are preferrable because they:
- use the standard dependency tooling everything else does
- don't require additional manual resolution or installation
- don't require a build process which performs installation steps
- don't overwrite the global Auspice install on build, which is
surprising at best and rude at worst
See the changes to the README for information on using local copies of
Auspice with `npm link`.
This commit reverts the commits "install auspice globally" (4e52c21) and
"allow auspice to be imported from a global npm installation" (f702df7).

Track the Auspice dependency in package.json like a normal dep

---

.travis.yml
README.md
package.json
redeploy-site.sh

Removes the need to manage this logic ourselves.

Switch to Heroku's native support for deploying after Travis CI checks are successful

---

auspice/server/getDataset.js
package-lock.json
package.json

By streaming the v2 JSONs to the client we reduce the memory needed by the server. This is made possible by the design of the v2 JSONs and auspice v2 which doesn't require any server-side modifications to the JSON data. 
See https://github.com/nextstrain/auspice/pull/825 for the same concept implemented in auspice.
Testing shows the following memory improvements (averages of a few runs & rounded to nearest 5Mb):
Baseline server memory usage (no requests): ~60Mb memory (unchanged). 
H3N2 12y dataset, minified (2.6Mb JSON): 75Mb -> 60Mb memory.
H3N2 12y dataset, indented (75Mb JSON): 290Mb -> 65Mb memory.

Stream v2 JSONs

---

auspice/server/getDataset.js
auspice/server/getDatasetHelpers.js
auspice/server/getNarrative.js
package-lock.json
server.js

Solves https://github.com/nextstrain/nextstrain.org/issues/50
Add a "/groups" prefix to Nextstrain groups URLs, like for `inrb-drc`,
to distinguish from and avoid namespace collisions with core Nextstrain
data sources.
Redirect old "inrb-drc" URLs to the new `/groups` endpoints.

Add "groups" prefix to Nextstrain groups URLs

---

server.js

1. The URL /groups shouldn't be handled by auspice. It will now currently displays the static-site 404 page, but in the future we will implement a page in the static site explaining what groups are.
2. Attempts to access /groups/x, where x is not a group, now show the static-site 404 page. Closes #67.

Restrict valid group urls

---

authn.js
static-site/src/components/splash/userGroups.jsx
static-site/src/pages/users.jsx

Centralize the computation of the list of sources visible to the current
user, but using a different property that doesn't conflate Cognito
groups with our internal sources.
Additionally, centralize the authz decisions to stay within the Source
object.
This change was originally [requested by Thomas on a recently closed
PR](https://github.com/nextstrain/nextstrain.org/commit/1a65e10b0094e74642668cea2abd58ae91420c19#commitcomment-36703817).

Detangle Cognito, sources, & group logic on authn

---

authn.js
static-site/src/components/splash/index.jsx
static-site/src/components/splash/userGroups.jsx
static-site/src/layouts/userDataWrapper.jsx
static-site/src/pages/users.jsx

In further testing of #74, we found an error when a user is logged-out
that prevented the splash page of nextstrain.org from loading.
Fix the error by checking if visibleGroups is defined in addition to
user before rendering the `<UserGroups>` component.

Fix visibleGroups is undefined error

---

auspice/server/sources.js
authn.js
static-site/src/components/Cards/index.jsx
static-site/src/components/Cards/padlock.js
static-site/src/components/Cards/styles.jsx
static-site/src/components/splash/styles.jsx
static-site/src/components/splash/userGroups.jsx
static-site/src/pages/users.jsx

See commit messages for more details.
@tsibley can you please review b70246f as it adds some static methods to the `Source` class(es) and modifies the `visibleGroups` function.
@trvrb are you happy with the UI here? It would be simple to show this `Nextstrain Groups` section on the splash page for everyone (i.e. non logged in users), and this wouldn't be too bad with the small number of groups we currently have, but I don't think it should be above the core tiles. Let me know if you want me to do this.
Available for testing at https://nextstrain-dev.herokuapp.com/
Closes #80

Identify public & private groups for logged in users

---

auspice/server/sources.js
auspice/server/utils.js

Previously `availableDatasets` for (private) S3 sources were not returning v2 JSONs. This commit creates a helper function to perform this task as we use it in multiple places.

Return v2 JSONs for private S3 sources

---

authn.js

When no REDIS_URL env var is set then we're running on localhost (or perhaps in a heroku review-app) and we store the session info in a FileStore. This was prone to spurious, but harmless, warnings printed in the terminal which was problematic for development. We no longer retry to access the session on disk (if it fails) which prevents these warnings.

Limit FileStore retries. Closes #39

---

static-site/content/docs/02-bioinformatics/03-augur-commands.md

The previous link of https://nextstrain-augur.readthedocs.io/en/stable/cli.html did not resolve anywhere. Now just like to the main `augur` docs.

fix broken link to `augur` docs

---

static-site/src/components/Cards/styles.jsx

Previously mobile tiles left a bunch of white space to the right. This fixes this with mobile tiles stretched to fill the entire display horizontally, while keeping the vertical clipping.

Update splash page tile display on mobile

---

auspice/server/getDataset.js
auspice/server/sources.js

The move to streaming of datasets caused `getDataset` requests for which the dataset didn't exist to _always_ return a 404 to the client. This wasn't the intention of the code -- for instance, community URLs should check `dataset.isRequestValidWithoutDataset` and return 204 if true, which wasn't happening.

Fix community errors

---

auspice/client/navbar.js

Before:
After:
_P.S. See https://github.com/nextstrain/auspice/pull/853 for an improvement in the title display_

Don't show nav-bar buttons when viewing narratives

---

redirects.js
server.js
static-site/src/components/splash/index.jsx

See commits. 
I chose to redirect nextstrain.org/narratives/ncov/sit-rep to the splash page instead of the current narrative as the latter would require us to update the server code as we updated the narrative. However we have to modify the server anyway (to update the splash tiles) so we could also keep this redirect pointing to the most recent narrative.

Add nCoV redirects

---

auspice/server/getDatasetHelpers.js
auspice/server/sources.js
auspice/server/utils.js

Community URLs may now include an alternate branch name with the syntax
`/community/<user>/<repo>@<branch>/…` to view datasets and narratives on a
branch other than "master".  If no branch is specified, "master" will be
used.
This change was made to allow translators of the 2019-nCoV narratives to
preview their work on their topic branches.

Support alternate Git branches for community sources

---

auspice/server/fetch.js
auspice/server/sources.js
docs/infrastructure.md
package-lock.json
package.json

This avoids repeatedly getting the same data from GitHub when nothing
has changed in the repo and thus avoids their unauthenticated API
rate-limit of 1 request per minute.  It makes loading of available
datasets and narrative lists much quicker too after the first time.
The make-fetch-happen package implements transparent caching just like
fetch() in the browser does.  The provided disk-based cache manager
should be sufficient for our needs.  It will be wiped every 24h by the
regular Heroku dyno restarts and by any deploy, but requests will just
be recached.  If it starts to have limitations, we can switch to caching
in Redis.
Additional verbose logging messages make it easier to troubleshoot
request or caching issues if they arise.

charon: Cache fetches to the GitHub API

---

static-site/src/html.jsx

Since Gatsby v2  CSS is inlined automagically and the explicit setup relying on existence of `public/styles.css` (previously containing a portion of styles to be inlined) is no longer necessary, and, even worse, fails the production build with an error: 
> Cannot find module '!raw-loader!../public/styles.css'.
because `public/styles.css` is no longer provided by Gatsby v2.
This PR removes the explicit setup and resolves the error. Complements #75. Resolves #104.
See discussion in:
- https://github.com/nextstrain/nextstrain.org/issues/104
- https://github.com/nextstrain/nextstrain.org/pull/75#issuecomment-574019845
Relevant gatsby docs:
- https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#remove-inlined-css-in-htmljs

fix(static-site): remove gatsby-inlined-css

---

static-site/.browserslistrc
static-site/gatsby-browser.js
static-site/package.json

This resolves nexstrain.org main page crash with console errors when using IE browser.
Changes:
- added polyfill for `fetch`
- changed babel's transpilation target to cover 99% of active browsers, including IE versions above 9 (inclusive).
Note: On this particular commit build is failing, until https://github.com/nextstrain/nextstrain.org/issues/104 is resolved. However I made it independent on the fix https://github.com/nextstrain/nextstrain.org/pull/108 to avoid collisions in case someone will have the build issues resolved earlier.
Verified with
- Internet Explorer 10.0.9200.17457
- Internet Explorer 11.0.9600.18920

fix(static-site): add polyfills and target config for Internet Explorer

---

static-site/package-lock.json
static-site/package.json

Resolves https://github.com/nextstrain/nextstrain.org/issues/113
Upgrades `gatsby-remark-autolink-headers` to version 2.1.24, which contains the necessary fix.

fix: crash on "let" keyword in IE

---

static-site/src/html.jsx

This fixes newer IE versions to paradoxically render blank page on nextstrain.org, while older versions work fine.
This fix prevents newer IE  versions (currently affected are 11.8xx and 11.9xx, but not 11.1xx or 10.xxx) to automatically switch to compatibility mode, in which case it is falling back to older IE standards. Apparently they fall back way to far, beyond our current compatibility (IE 10+).
"Edge" content value of this tag tells IE and Edge, no matter which version, to enable its latest available features and to not enable compatibility with older versions.
This tag should come very first in the `<head/>`, otherwise preceding tags may be interpreted in older mode, before browser switches to "edge" mode.
Note, that this tag may be ignored if compatibility is set in IE developer …

fix(static-site): add X-UA-Compatible meta tag for IE doc mode

---

auspice/client/languageSelector.js

This does not solve the problem, but temporarily patches  https://github.com/nextstrain/auspice/issues/902, unlocking nextstrain.org users with some of the older browsers.
This works by forcing the import of ES5 version of `iso-639-1`

Workaround to ensure that ES6 classes don't leak into the bundle from iso-639-1 package

---

static-site/content/help/02-coronavirus/01-human-CoV.md
static-site/content/help/02-coronavirus/02-SARS-CoV-2.md
static-site/gatsby-node.js
static-site/src/components/Sidebar/index.jsx
static-site/src/templates/displayMarkdown.jsx
static-site/src/util/structureEdges.js

Adds support for `anchorText` in posts. This allows the author to customize the anchor text in the left hand menu.
Fixes #137 
This change can be tested by visually inspecting the site.
cc @chrisq21 I started working on this PR without looking at the comments yesterday. Happy to go with your solution. But I figured I'd share mine just in case! thanks

Fix title case hyphen issue

---

static-site/src/components/Cards/coreCards.js
static-site/src/components/Cards/index.jsx
static-site/src/components/Cards/nCoVCards.js
static-site/src/components/Cards/styles.jsx
static-site/src/components/splash/index.jsx
static-site/src/components/splash/userGroups.jsx

Here we add the regional builds as tiles to the splash page. 
As we now have so many nCoV cards (due to all the amazing translations) we set these cards to be "squashed" so that they take up less vertical space. 
We also make minor changes to the title: 
```diff
- Novel coronavirus (2019-nCoV)
+ Novel coronavirus
- We are incorporating nCoV genomes as soon as they are shared and providing analyses and situation reports.
- Please see below for the latest updates.
+ We are incorporating SARS-CoV-2 genomes as soon as they are shared and providing analyses and situation reports.
+ Please see below for the latest analyses and situation reports.
```

Add regional builds to splash page & squash tiles.

---

static-site/content/docs/02-bioinformatics/05-data-formats.md

updates the links to schema data found in https://nextstrain.org/docs/bioinformatics/data-formats.  
can be tested locally with
- npm run build in the nextstrain directory 
- wget --spider -r -nd -nv -H -l 1 -o nextstrain.log https://localhost:5000/docs/bioinformatics/data-formats
- grep -B1 'broken link!' nextstrain.log (should return empty)
fixes #147

update broken links in docs

---

static-site/content/docs/03-tutorials/03-defining-clades.md

In the phrase: Along the same lines, there are six mutations defining clade `c7`, and thus there are six entries in the `tsv` file.
The c6 should be a c7, according to the data in the section.
Fixes #  N/A
Related to #  N/A
What steps should be taken to test the changes you've proposed?  N/A
If you added or changed behavior in the codebase, did you update the tests, or do you need help with this?  No. Fixing a typo.

Fixing Typo in Section: Make a TSV File Containing your Clade Mutations

---

docs/groups.md
src/sources.js

Adds /groups/swiss for @emmahodcroft and @rneher and co. Clarifies groups doc a bit.

Add /groups/swiss + minor doc updates

---

static-site/content/docs/01-getting-started/04-local-installation.md

This replaces the specific instructions of how to install augur and auspice using pip and npm respectively with links to their own documentations, so that these instructions don't become out of sync with the latest install practices for either tool. 
This is one of multiple such PRs I will be submitting as we try to deduplicate things between the nextstrain.org docs and other docs, while **aiming not to have too many links buried in text on the nextstrain.org docs such that they are not found when folks are looking for them.**
One strategy I've discussed with @jameshadfield to accomplish that aim is to (where possible) instead of replacing some chunk of text in a given document with an external link, try to break up the information in that document into seperate documents so that sections …

Link non-conda install methods to respective docs

---

static-site/content/docs/05-contributing/01-sharing-data.md

Just adding another row to the table of [the new sharing data page](https://nextstrain.org/docs/contributing/sharing-data) for nextstrain maintained pathogen builds (please correct me on where that data lives if I got it wrong) and changing the 
> Bespoke auspice deployments
heading to be consistent with the relevant table entry:
> Custom auspice servers
#164
Tested locally with Gatsby

sharing data doc: consistent headings + table

---

static-site/content/docs/02-bioinformatics/05-data-formats.md

Link out any details on augur output and auspice input to their respective docs so they don't get out of sync with those docs, while providing the necessary high-level info about how the two relate when it comes to data formats. The ideal goal would be to inject that content into nextstrain.org docs to avoid users having to follow too many links.
Also adds a link to [the new page describing ways to share results](https://nextstrain.org/docs/contributing/sharing-data)
#164
https://github.com/nextstrain/auspice/pull/1127
Tested links worked locally with Gatsby.

link out data formats to augur and auspice docs

---

static-site/content/docs/05-contributing/03-documentation.md

1. Add a blurb making it clear what information should go in the nextstrain.org documentation vs augur, auspice.
2. fix local static site build instructions. Despite my changes to the static site build instructions, I think this [importing code from auspice-client/customisations into the static-site](https://github.com/nextstrain/nextstrain.org/pull/156/files?file-filters%5B%5D=.json&file-filters%5B%5D=.jsx#diff-8e56725b3447679dcf1c6b67981162afR14 ) means we have to install the root repo node dependencies in addition to the static-site ones even if we just want to run the static site (i.e. if someone is following the instructions in the [document in question](https://nextstrain.org/docs/contributing/documentation#building-the-documentation-locally) here with a fresh clone). Although …

Add blurb clarifying various project docs

---

static-site/content/docs/05-contributing/04-development.md

Replace the [list of links to github repos for various nextstrain projects](https://nextstrain.org/docs/contributing/development) with one link to the github nextstrain organization contributing guide. It seems like a great document for this purpose, i.e. a top level guide to contributing to the various nextstrain.org projects.
#164 
Locally with gatsby + testing links work.

Replace list of github links with link to organization contributing guide in docs

---

static-site/content/docs/05-contributing/03-documentation.md

We no longer need python to build the static site so this removes it from the build instructions
#172

remove python listed as static site dep

---

static-site/content/docs/07-visualisation/01-download-data.md

Copy edits etc welcome!
This PR must be merged after #176 as the downloading of diversity (entropy) data is only available with auspice 2.16.

add download data documentation

---

.gitignore
README.md
build.sh
package-lock.json
package.json
scripts/collect-exclusions-sars-cov-2.js
scripts/collect-strains-sars-cov-2.js
static-site/gatsby-node.js
static-site/package-lock.json
static-site/package.json
static-site/src/pages/ncov-sequence-to-dataset.jsx
static-site/src/pages/sars-cov-2-sequence-search.jsx

This introduces functionality which we've talked about previously but was sorely needed by me today! It works, but there are plenty of optimisations and improvements we could make. Consider this a Friday afternoon project (which is what it was). 
During `npm run build` we scan all the nCoV datasets (currently looking at the staging bucket) and generate a git-ignored JSON file mapping the sample names to which dataset they appear in.
A new page /ncov-sequence-to-dataset provides a search box For a single sample name, you'll get a chronological list of datasets which it appears in. For multiple samples, you'll get a list of datasets where they all appear together.
Limitations:
* React Select is slow with this many items
* The JSON file is only regenerated when the server restarts (when `npm …

Add page where you can search samples across datasets

---

src/sources.js

This will allow Nextstrain groups to customize their logo/avatar on
the groups splash page by uploading `logo.png` to their S3 bucket.
I've added `logo.png` for SeattleFlu, which can be seen at `localhost:5000/groups/seattleflu`

S3Source: return `group-logo.png` as avatar if found in S3 bucket

---

README.md
static-site/content/docs/01-getting-started/01-introduction.md
static-site/content/docs/01-getting-started/02-quickstart.md
static-site/content/docs/01-getting-started/05-container-installation.md
static-site/content/help/01-general/01-about-nextstrain.md

Here we add links to the (new) discussion site in the majority of the places where we provide a contact email address. There are exceptions to this, such as the nextstrain.org splash page where as we wanted to direct more casual users to use the email for the time being.

Add links in documentation pointing to discussion.nextstrain.org

---

README.md
static-site/content/docs/01-getting-started/01-introduction.md
static-site/content/docs/01-getting-started/02-quickstart.md
static-site/content/docs/01-getting-started/05-container-installation.md
static-site/content/help/01-general/01-about-nextstrain.md

These have to be absolute links because they are not relative to nextstrain.org/.

Fix links to discussion.nextstrain.org

---

.travis.yml
README.md
build.sh
static-site/package.json

1. We use npm to install project dependencies in two places: the root level and within the `static-site` directory (via `build.sh` or `npm run build`). Moving to `npm ci` allows (a) developers to all be working from the same deterministic set of dependencies and (b) the automatic deploys (heroku, travis) to use the same dependencies as us.
2. This updates travisCI to use the version specified in package.json, which heroku will run. This results in a CI which better matches our actual deploy environment.
Also changed the `engines` declaration of the static-site to match the root level declaration (I don't believe anything was / is using the static-site engines declaration, but it should match the root level as we are running both from the same environment).

Update build ci

---

static-site/additional_sidebar_entries.yaml
static-site/src/components/Sidebar/index.jsx

We've wanted the ability to provide external links to docs pages -- for instance the new nCoV tutorial which is hosted by github pages for the ncov repo. 
This commit sets up the ability to do this for a curated set of entries (in a YAML file), and indicates that they will go to an external doman via a icon next to them in the sidebar.

Add external links to docs pages in sidebar

---

package-lock.json
package.json
src/getDatasetHelpers.js

The HTTP status line message is not intended for arbitrary messages and
not suitable for freeform text due to character restrictions.
Using statusMessage this way has caused nextstrain.org server crashes
when the field is assigned an error containing a newline, as newlines
are not allowed.
Resolves #201.
Related to <https://github.com/nextstrain/auspice/issues/1180>.
---
A draft PR for now as one more commit is still needed to upgrade Auspice to the next released version that includes PR https://github.com/nextstrain/auspice/pull/1181. Will wait for that to merge and release before adding the final commit here.

Send error messages in the response body, not the status line

---

static-site/content/docs/01-getting-started/02-quickstart.md
static-site/content/docs/02-bioinformatics/02-what-is-a-build.md
static-site/content/docs/03-tutorials/01-zika.md

Adds the required --cores 1 argument to all calls to `snakemake` and `nextstrain build` in documentation. This is the first step toward [removing Snakemake as an augur dependency](https://github.com/nextstrain/augur/pull/557).

Document required cores argument for snakemake and nextstrain build

---

package-lock.json
package.json
src/getNarrative.js

Auspice PR nextstrain/auspice#1172 allows narrative parsing to be performed client-side. Once that PR is merged, auspice will make `getNarrative` GET requests with a `type=md` query and expect the markdown content to be returned as the response (although it will still handle a JSON response for backwards compatibility.) This PR updates the nextstrain.org server's `/charon/getNarrative` handler to stream the markdown file as a response.
~Before merge, a new auspice release will be made and this PR's imported version updated accordingly~ Updated to use auspice 2.18
@tsibley @kairstenfay @joverlee521 could you review the approach taken here? It is conceivable that `getNarrative` requests are made to this server from outside of nextstrain.org, which will now fail, but I consider this unlikely …

wip: parse narratives on client

---

src/sources.js

The API we were using to access the datasets behind nextstrain community didn't work if the file was stored using git-lfs (the response was a 200 with the contents of the git-lfs pointer). We now switch to a different GitHub API call which allows us to access both "normal" github files and those stored with git-lfs.
Underneath, this new API returns a 302 redirect to one of two different APIs. If the file is "normal", the redirect is to the previous API we were using (raw.githubusercontent.com), if it's git-lfs then it redirects the request to the media.githubusercontent.com API.
URLs to test: 
* https://nextstrain-s-git-lfs-co-izv8nx.herokuapp.com/community/czbiohub/covidtracker/ca (git-lfs)
* https://nextstrain-s-git-lfs-co-izv8nx.herokuapp.com/community/emmahodcroft/south-usa-sarscov2/lo …

Allow community builds to be stored using git-lfs

---

.github/workflows/update-search.yml

This is a Github action which runs `scripts/collect-search-results.js` and uploads this data to s3 in order to update https://nextstrain.org/search/sars-cov-2. It is scheduled to happen every weekday as close as possible to the time by which we have usually published new sars-cov-2 (ncov) builds to s3; as I wrote in a comment in the workflow itself, the timing of this is imperfect for sars-cov-2 (ncov) builds because they are run in different time zones on alternating days. More jobs in this workflow or separate ones with separate timelines can be added for other pathogens we want to maintain search pages for. If we want to make this 'smarter' we can use something like aws lambdas which could automatically run upon updating of certain files in an s3 bucket, but that doesn't seem to be …

Update sars-cov-2 search regularly

---

src/getAvailable.js
src/sources.js

Refactor the computation of second tree options data by moving it into
the getAvailableDatasets() method of the Source classes.
Note that it still uses globally computed data for now. While stopping
or centralizing the usage of global variables is a desirable direction
to take this codebase, this commit is just moving the functionality to a
place it's more expected.

Refactor secondTreeOptions

---

src/exceptions.js
src/getAvailable.js
src/getDataset.js
src/getDatasetHelpers.js
src/getNarrative.js
src/getSourceInfo.js
src/sources.js
src/utils.js
test/smoke-test/auspice_client_requests.json

Change the error handling for client errors.
Previously, we were treating incorrectly typed (or non-parseable) URLs as 500 errors, when in my opinion, we should be returning a response of a 400 error, indicating that the request was bad because the query was malformed. 
~This branch is currently based off of #227 to minimize the differences shown here between it and the master branch.~

Error handling

---

static-site/content/allSARS-CoV-2Builds.yaml
static-site/src/components/sars-cov-2/build-map.jsx

This uses a react-mapbox-gl component to cluster builds on the map. Only community builds are clustered in this way. Clicking a cluster will zoom to the bounds of the builds it contains. Cluster tooltips don't show the contents of the
cluster (this is possible, just adds complexity to implementation). Important to note that clusters will never separate if two markers (builds) have the same coordinates. Since programmatically adding small differences to identical coordinates is non-trivial, we do this manually in the yaml file for now. We should add a console warning so that this doesn't happen by mistake.
Fixes #  
Related to #  
If you added or …

[build-map] cluster community builds on the map;

---

static-site/content/allSARS-CoV-2Builds.yaml

This PR adds the [Washington State SARS-Cov-2 build](https://nextstrain.org/groups/blab/ncov/wa/4m) to the global map.

Adds WA build to map

---

static-site/content/allSARS-CoV-2Builds.yaml

This PR adds the Baele Lab's Belgium-focused build to the map.
In addition to adding the new build (centered Leuven), coordinates for the Neher Lab's currently existing build have been shifted slightly to Brussels center so that the two builds can be differentiated on the map.

Add BE build to map

---

static-site/content/allSARS-CoV-2Builds.yaml

URL contained underscore instead of hyphen for white space in country names
Fixes https://github.com/nextstrain/nextstrain.org/issues/249 by replacing faulty underscore with hyphen

Fixed build URL data for UK and Czechia

---

package-lock.json
package.json
scripts/check-sars-cov-2-builds-yaml.js
static-site/content/allSARS-CoV-2Builds.yaml
static-site/src/components/sars-cov-2/build-map.jsx
static-site/src/components/sars-cov-2/builds.jsx

Removing some unnecessary `null` fields in this yaml listing of sars-cov-2 builds and adjusting the code to allow them to be undefined instead. Also moves all the hierarchy defining builds to the top for easier reading (I think, though can revert this if others disagree).

Sars-cov-2 builds yaml clean up

---

static-site/content/allSARS-CoV-2Builds.yaml

Deleted tickmark ` after South America name
Fixes https://github.com/nextstrain/nextstrain.org/issues/256

Fixed typo in allSARS-CoV-2Builds.yaml

---

package-lock.json
package.json

This includes an important update to how auspice client JS chunks
are named which should prevent bugs where a browser would use an
out-of-date cache due to the chunk filenames remaining unchanged.

Upgrade auspice to 2.22.2

---

static-site/content/allSARS-CoV-2Builds.yaml

This is PR #258 with slight change to the build names so that they are clearer when hovering on the map and the addition of ontario as a heirachy block in the YAML which is necessary for inclusion in the table.
Awesome to see another auspice server being run!

Add public canada nCoV builds

---

static-site/src/pages/sars-cov-2.jsx

The list of SARS-CoV-2 resources currently links to the README for CoVariants on GitHub, but most users would find a direct link to the live CoVariants site more useful.

Link to actual CoVariants site, not GitHub README

---

static-site/content/allSARS-CoV-2Builds.yaml

Adds all state- and territory-level builds maintained by SPHERES (CDC/AMD) to the map and USA SARS-CoV-2 lists.

Add SPHERES/CDC builds to SARS-CoV-2 page

---

README.md
auspicePaths.js
develop.sh
package.json
server.js
static-site/README.md
static-site/gatsby-config.js
static-site/package-lock.json
static-site/package.json

Closes #158. From https://github.com/nextstrain/nextstrain.org/issues/158#issuecomment-789871596:
> So, my approach is similar to option 1, which is running both the dev-server and gatsby dev server, but I take advantage of Gatsby's built-in development API proxy (https://www.gatsbyjs.com/docs/api-proxy/).
> I made a proof-of-concept in my fork https://github.com/didithilmy/nextstrain.org/tree/use-gatsby-dev. Try to run npm run dev from the root directory.
> Unfortunately, it involves Gatsby knowing what paths are NOT supposed to be served by Gatsby, which is located in server.js, outside static-site. In my solution, I moved the auspicePaths into a separate file, which is included by static-site/gatsby-config.js.

Use Gatsby dev to proxy dev-server

---

static-site/src/components/build-pages/dataset-select.jsx

this was previously hardcoded to be a
nextstrain logo. I replace it here with a
person icon for non-Nextstrain contributors
will merge right away since its a 1 commit quick fix to #286 and people might be mad if they view /sars-cov-2 on mobile and it looks like we are crediting ourselves for their datasets.

dataset-select mobile view contributor links;

---

authn.js
package-lock.json
package.json

Cuts out two requests on every login: one to the user info endpoint and
another to the Cognito admin list user groups endpoint.  This also
avoids the server needing AWS credentials with admin permissions in
Cognito.
The verifyToken() function will be useful when we start accepting tokens
directly for authorizing API requests (e.g. from the CLI).
Resolves #277.

authn: Use claims from Cognito tokens instead of making additional requests

---

static-site/src/components/Datasets/dataset-select.jsx
static-site/src/components/Datasets/filter-helpers.js
static-site/src/components/Datasets/filter-selection.jsx

This adds the dataset contributor as a keyword for the filtering of datasets in the dataset-select component. In some cases this results in duplicate or near-duplicate keywords if the contributor name is also in the dataset name.
It doesn't add contributor keywords if the datasets are all from the same contributor.

dataset-select filter by contributor

---

static-site/src/components/Datasets/dataset-select.jsx
static-site/src/components/Datasets/filter-helpers.js
static-site/src/components/Datasets/filter-selection.jsx
static-site/src/components/Datasets/list-datasets.jsx
static-site/src/pages/influenza-page.jsx
static-site/src/pages/sars-cov-2-page.jsx

This commit creates a more flexible react pattern that allows pages
(e.g. /influenza, /sars-cov-2) to decide which columns are rendered,
as well as how they look (e.g. logo, mobile text, links etc).
In turn, this will give us the ability for different pages to use
different dataset structures and display bespoke information in the
table.
Currently the number of columns must be 2 or 3, and the 3rd will
not be rendered for small screen sizes. This could be improved in
future as needs arise.
Based on work by @eharkins in PR #289. @eharkins has already reviewed a previous iteration of this PR, and this has been updated accordingly.

Pages can define which columns are rendered

---

.eslintrc
static-site/src/components/Datasets/dataset-select.jsx
static-site/src/components/Datasets/filter-display.jsx
static-site/src/components/Datasets/filter-helpers.js
static-site/src/components/Datasets/filter-selection.jsx
static-site/src/components/Datasets/list-datasets.jsx
static-site/src/components/Datasets/styles.jsx
static-site/src/pages/influenza-page.jsx
static-site/src/pages/sars-cov-2-page.jsx

This PR is based off commits 9733985, a8db4cb and 491682e (all by @eharkins, see PR #291). The main changes are due to the refactoring previously done in #299.
The `interface` prop passed to `<DatasetSelect>` (originally implemented in 9733985) has been generalised to take any number of (react) components as props, although this is only currently used by the geographic map in sars-cov-2.

Allow pages to define and inject dataset-related components

---

auspicePaths.js
package.json
redirects.js
server.js
src/parentPage.js
static-site/gatsby-config.js
static-site/gatsby-node.js
static-site/src/sections/staging.jsx
test/unit/routing.test.js

Begins an implementation which would close #310. See commit messages for more information.
Currently works with core and staging URLs. All other sources (groups, community etc) are still handled by Auspice. Here are some trial URLs:
* https://nextstrain-s-redirects--ouuvbt.herokuapp.com/flu/vic/yam Invalid flu URL, shows main influenza page instead. 
* https://nextstrain-s-redirects--ouuvbt.herokuapp.com/ncov/antartica ncov dataset which doesn't exist. Shows SARS-CoV-2 main page.
* https://nextstrain-s-redirects--ouuvbt.herokuapp.com/ebola/equateur dataset doesn't exist. Shows the splash page, as we don't yet have a page listing all core datasets.
* https://nextstrain-s-redirects--ouuvbt.herokuapp.com/staging/no-dataset shows new staging page listing datasets & narratives.
(Note that the …

List available datasets in Gatsby (not Auspice)

---

package-lock.json
package.json
redirects.js
server.js
src/exceptions.js
src/getAvailable.js
src/getDataset.js
src/getDatasetHelpers.js
src/getSourceInfo.js
src/sources.js
src/utils.js

Switches to async-friendly Express routers. Async-friendly routers eliminate the need for most of our own try/catch blocks around internal awaits, as they automatically catch exceptions and send an appropriate error response.  This also lets us start throwing exceptions for HTTP error codes instead passing around the Express response object.
Few immediate functional changes, but this enables future simplifications as we touch other code paths. As an example, the 404 handling is now much simpler.
Reviewing https://github.com/nextstrain/nextstrain.org/pull/317 made me recall that on a local work-in-progress branch I had a similar fix for the 500 error on unknown sources that included these broader error-handling changes. I've rebased them off of that WIP, which was focused on entirely …

Improve async error handling in routes

---

static-site/src/components/nav-bar/index.jsx
static-site/src/components/splash/index.jsx
static-site/src/components/splash/userGroups.jsx
static-site/src/layouts/generic-page.jsx
static-site/src/layouts/userDataWrapper.jsx
static-site/src/sections/users.jsx

Instead of requiring that children components be nested directly
beneath the userDataWrapper component in order to use its state
(by cloning all children of the wrapper and passing props to each),
this uses react's Context (https://reactjs.org/docs/context.html)
to allow children at any nesting level within userDataWrapper to
access its state.
Needs testing. Useful for #316 and #314

use react context for userDataWrapper;

---

auspicePaths.js

This change produces a reproducible increase in speed when testing
locally using the /zika dataset of c. 120ms vs 150ms (HEAD vs GET
methods). For datasets which don't exist (e.g. /zika/no), as expected
there is little change (both methods take c. 280-300ms; longer times
are expected as we make a second request for the v1 dataset).
Larger datasets should experience a larger speed improvement here.
Cacheing of status codes would be another avenue to pursue to improve
speed for this middleware, but that carries its own downsides.

Request headers-only to check dataset existence

---

.travis.yml
server.js
src/getDataset.js
src/getDatasetHelpers.js
src/getNarrative.js
src/sources.js
test/smoke-test/auspice_client_requests.json

When running this server daa8ff64348920f8a804728808a8a6de1503a2d6 both live (nextstrain.org) and locally, I was experiencing hard-to-reproduce errors when viewing community splash pages (e.g. /community/jameshadfield/scratch). This is related to the recently deployed #320, however it only occurred when the server requested data from GitHub. Hitting GitHub's API limits during testing didn't help either.
Investigating this led to a grab-bag of server improvements - see commit messages for more. 
One big improvement is the integration of smoke-testing in our CI runs, which ~may have~ would have identified this before deployment.

Improve charon API handlers

---

src/getDataset.js

This object takes c. 16 lines of the logs each time and was
cluttering up logging with no obvious benefits. If has benefits
for development purposes, and a better long term solution
would be different levels of verbosity.

Reduce verbose server logging

---

README.md
develop.sh
docs/infrastructure.md
server.js

These additions were originally motivated by reviewing #320. See commit messages for further details.
A lot of the README would be better suited as pages within `./docs` such as `development.md`, or more siloed pages such as `{server-development.md, gatsby-development.md, auspice-development.md}`, however that's a bigger task than it first appears and so I'm leaving that for another PR.

Dev docs update

---

package-lock.json
package.json
src/sources.js

Accessing datasets and narratives in public & private groups relies
on using the AWS-SDK to access objects in the underlying S3 buckets.
The SDK silently loads credentials, if available [1].
If credentials are _not_ supplied, then access to private groups fail
with a suitable warning printed; however calls into public groups,
backed by publicly accessible buckets, simply hung (AWS method
`S3.listObjectsV2`) until the request timed out (`ETIMEDOUT`).
We now check to see if credentials are supplied, and if they are not,
skip the calls into S3 and log a warning instead.
If credentials were supplied, but they were invalid, then a fatal
`InvalidAccessKeyId` error was thrown. We now catch this and print a
warning.
In both cases the Source class method (`_listObjects`) will return an
empty …

Allow server to work without AWS credentials

---

auspicePaths.js
static-site/gatsby-node.js
static-site/src/components/splash/errorMessages.jsx
static-site/src/sections/individual-group-page.jsx

For /groups/:groupName/*
If groupName doesn't exist, we show a message with a link to /groups.
If groupName does exist but * isn't a dataset in that group,
we show /groups/:groupName with a message saying * doesn't exist.

/groups/:groupName 404 improvements;

---

static-site/package-lock.json
static-site/package.json
static-site/src/components/splash/groupHeading.jsx
static-site/src/components/splash/markdownDisplay.jsx
static-site/src/util/parseMarkdown.js

Copies auspice approach:
https://github.com/nextstrain/auspice/blob/master/src/util/parseMarkdown.js
but uses "sanitize-html" library:
https://github.com/apostrophecms/sanitize-html
A couple of config options from the auspice approach
didn't seem to have analogous options in the library I
use here. Also I don't add a hook to set the <a> tags
to open links in a new tab as is done in auspice. There's
probably a way to set this with the "sanitize-html" library
but it wasn't obvious to me and it wasn't working anyway
on nextstrain.org groups pages (which was using the auspice
code to parse markdown until recently for groups pages).

parse /groups/:groupName markdown;

---

redirects.js
static-site/gatsby-node.js
static-site/src/components/splash/styles.jsx
static-site/src/pages/community.jsx
static-site/src/pages/groups.jsx
static-site/src/sections/pathogens.jsx
static-site/src/sections/staging.jsx

The `/pathogens` page as discussed. Essentially duplicates the code for `/staging` page for now pending a refactor with reusable components (#347) once they are ready for use.

/pathogens

---

static-site/src/components/splash/errorMessages.jsx
static-site/src/layouts/generic-page.jsx
static-site/src/sections/individual-group-page.jsx

creates a generally applicable
ErrorBanner component to be passed
as the `banner` prop to GenericPage.
ErrorBanner takes `title` and `contents`
props.
Current examples can be seen on the
individual-group-page.jsx page, e.g.
/groups/not-a-group
/groups/not-a-group/not-a-dataset
/groups/blab/not-a-dataset

ErrorBanner component

---

auspicePaths.js

The intention of the code modified in this commit was to pass
all URLs which represent narratives to Auspice, as the ability
to determine narrative existence is not yet incorporated by
`isRequestBackedByAuspiceDataset` (which may need to be renamed!).

Fix bug serving narratives for groups

---

auspicePaths.js
src/sources.js

This new parameter is only relevant for the method in the child class
`PrivateS3Dataset` which needs to know which operation to pass
to `S3.getSignedUrl()`.

Dataset.urlFor(): add `method` parameter

---

static-site/gatsby-node.js
static-site/src/sections/pathogens.jsx
static-site/src/sections/staging.jsx

we were attempting to prefilter
listings on these pages according
to the * in e.g. /pathogens/* but
this was causing issues with linking
to auspice datasets from these pages.
This is not a high priority feature
and was not advertised yet so this
removes it (for now) to make sure
linking to auspice datasets from these
pages functions correctly.

remove matchPath for /pathogens and /staging;

---

static-site/src/util/parseMarkdown.js

Valid-looking URLs which we expect to be commonly used in markdown
(and, indeed, are being used in at least two group overviews) can
result in `new URL()` throwing a `TypeError`. Instead of failing
to parse the markdown, we instead allow the URLs but add the
suitable tags to the `<a>` element.
Closes https://github.com/nextstrain/nextstrain.org/issues/361

Improve markdown parsing of URLs

---

auspicePaths.js

The recent code which checked for dataset existence (in order to route to Auspice or Gatsby) failed to take into account tangletree URL syntax, resulting in the inability to load any tangletrees from a URL. Here we implement a simple fix by only considering the first dataset of a tangle-tree-like URL. Note that Auspice will display a 404-like page if either of the datasets in a tangle-tree URL don't exist, so the solution implemented here is les-than-ideal.

Fix URL parsing of tanglterees

---

redirects.js

Currently all core nCoV builds have used GISAID data, and have been
available at URLS /ncov/global, ncov/asia, etc. The nextstrain/ncov
PR #628 [1] updates our workflow to produce builds for both GISAID and
GenBank data sources, which will result in URLs /ncov/gisaid/:region and
/ncov/genbank/:region, respectively.
Links such as /ncov/:region are heavily used and are assumed to mean
"the latest analysis for :region using GISAID data". This commit
adds redirects so that /ncov/:region now goes to /ncov/gisaid/:region.
Note that this commit should only be merged after [1] has been merged
and a build successfully completed, which will produce the files
s3://nextstrain-data/ncov_{:region}.json.
[1] https://github.com/nextstrain/ncov/pull/628

Redirect core (GISAID) nCoV URLs

---

.github/workflows/update-dataset-listings.yml
.github/workflows/update-flu-catalogue.yml
scripts/collect-datasets.js
static-site/src/sections/staging.jsx

Currently the /staging page uses a /charon request
to source its dataset listing via the manifest. Here we
change to doing the following instead:
- Collect staging datasets with scripts/collect-datasets.js
script and publish this list to s3 in a github action
- On /staging we request this listing from s3 to show a more
frequently updated listing than with the manifest
This strategy is a comprimise between existing attempts:
(1)  using the manifest via a /charon request (current)
(2) crawling the s3 bucket via a /charon request (see https://github.com/nextstrain/nextstrain.org/pull/362)
in that it crawls the s3 bucket but on a regular interval
instead of with each request. Requests are made to a static
listing which is regenerated every 5 minutes (at no cost to the
nextstrain.org server). …

collect staging datasets instead of use manifest;

---

redirects.js

Fixes a bug introduced by #350 where we lose query params when redirecting from e.g. https://nextstrain.org/ncov/africa?f_region=Africa and get https://nextstrain.org/ncov/gisaid/africa without the region filter query param.
Needs more testing and review as I'm not an expert in express.js. Also we redirect many other URLs, so might be worth having a look at doing something similar where appropriate among other existing redirects for nextstrain.org.

preserve query params in gisaid builds redirects

---

auspicePaths.js
static-site/src/sections/community-page.jsx

#368 implemented error behavior for various
pages including /community/*. In the case of
/community/* pages, this broke the ability to
visit a list of available datasets at a url like
/community/:user/:repo where user and
repo are valid [1].
Since we don't yet have /community/:user/:repo
splash pages in gatsby to list datasets, this
reverts to sending those to auspice to list datasets
for now.
A final note that when we do implement such pages,
they should be the ones to catch errors about invalid
user, repo, or dataset names, as opposed to the
top-level /community splash page. This is how we do
it for /groups as well.
[1] https://github.com/nextstrain/auspice/issues/1378

fix community splash pages;

---

static-site/src/sections/individual-group-page.jsx

This helps with development, as clicking on the dataset/narrative
will use the current (dev) server, rather than nextstrain.org

Relative URLs on individual groups pages

---

static-site/src/components/Cards/communityCards.js
static-site/src/components/Cards/coreCards.js
static-site/src/components/Cards/index.jsx
static-site/src/components/Cards/nCoVCards.js
static-site/src/components/Cards/narrativeCards.js
static-site/src/components/Cards/styles.jsx
static-site/src/components/splash/index.jsx
static-site/src/components/splash/userGroups.jsx
static-site/src/sections/community-page.jsx
static-site/src/util/parseMarkdown.js

temp solution for cards is to allow the Cards
component to use flexbox instead of bootstrap
for a more compact, two-column layout. This
will be refactored when we address the design
and flexibility of these components in #305, #347.
TODO:
- might need to unsquash ncov and narratives cards
to be able to read them on mobile
- allowing page sections to tile horizontally,
e.g. groups alongside sars cov 2 as in james' sketch
- more testing

splash page redesign; #388;

---

static-site/src/components/Cards/fluCards.js
static-site/src/components/Cards/pathogenCards.js
static-site/src/components/Datasets/pathogen-page-introduction.jsx
static-site/src/sections/influenza-page.jsx
static-site/src/sections/pathogens.jsx

Perhaps misleading to exclude the two influenza
cards which are on the splash page from this selected
list of pathogens on the /pathogen page? Could imagine
someone clicking "see all pathogens" underneath the
two influenza cards wanting to see a list including those
two influenza cards. My reason for not including them
was the niceness of the 3x3 grid without them.

Add coreCards back to /pathogens;

---

src/app.js

Otherwise the /staging/* route ends up matching with an empty dataset
path, throwing an error, and the request never hits the Gatsby static
file tree where it would match /staging/index.html.

Send the Gatsby splash page for /staging

---

package.json

The currently used node version `13` [has already reached end-of-life status](https://github.com/nodejs/Release#end-of-life-releases) and is preventing auspice npm updates from working on nextstrain.org (#437, https://github.com/nextstrain/auspice/commit/bec41d6ad42cbb500da81d2a240af7f349d7db42)
Choice of `14` is mostly due to consistency as it is already used in GitHub actions:
- [update-dataset-listings](https://github.com/nextstrain/nextstrain.org/blob/04acaaffe766274ded930b6cafc55b75df8c1311/.github/workflows/update-dataset-listings.yml#L16)
- [update-search](https://github.com/nextstrain/nextstrain.org/blob/04acaaffe766274ded930b6cafc55b75df8c1311/.github/workflows/update-search.yml#L22)
Also updating npm version to 6.14.x since it corresponds with node=14 per …

Use node version 14

---

src/app.js

We may want to publish these files elsewhere in the future, but this is
a easy place to start with barely any new overhead.
See also https://github.com/nextstrain/augur/pull/806.

Resolve our JSON Schema $id URLs by redirecting to the files on GitHub

---

docs/infrastructure.md
src/sources/community.js
src/sources/core.js

This will alleviate somewhat the rate limits imposed on unauthenticated
requests.  As of this writing, authenticated requests get 5,000
requests/hour per authenticated user (_not_ per token).  Unauthenticated
requests get only 60 requests/hour per IP.¹
Resolves #93.
Other future changes to address rate limiting might include switching
from simple fetch()es to an API client that does dynamic throttling to
respect the rate limits.  Octokit does a great job of making this easy,
for example.²  Complications with using Octokit include figuring out how
to incorporate our current caching, or an equivalent. Caching is an
important part of reducing these requests.  Another complication is how
long to retry before returning a 500 error to the nextstrain.org
request; the example above retries …

Authenticate requests to the GitHub API (optionally)

---

static-site/gatsby-node.js
static-site/src/sections/community-page.jsx
static-site/src/sections/community-repo-page.jsx
static-site/src/sections/individual-group-page.jsx
static-site/src/sections/staging-page.jsx

These splash pages also serve as 404 pages for matching paths beneath
their respective sections.  Previously the pages assumed the
non-existent path was always for a dataset.

Handle non-existent narratives on our various splash/404 pages

---

static-site/content/SARS-CoV-2-Datasets.yaml

Hello Nextstrain Team,
This a request to add our SARS-CoV-2 dataset. Our goal is to provide a public build and help the local scientific community keep track of the circulating SARS-CoV-2 strains in Puerto Rico. The github repository is [https://github.com/arodzh-sudo/ncov-puertorico](https://github.com/arodzh-sudo/ncov-puertorico).
Earlier in the pandemic, sequences from Puerto Rico were uploaded to GISAID as North America / USA / Puerto Rico. Currently, almost every sequence is uploaded as North America / Puerto Rico. For this build, I changed the color_ordering and lat_longs files to reflect this.
If you notice, I added to the code (to also reflect the change):
region: North America
level: country
There is one other build focused on Puerto Rico maintained by the CDC/AMD which has: …

Update SARS-CoV-2-Datasets.yaml - Puerto Rico Public Health Laboratory Nextstrain Build

---

src/sources/community.js

Resolves #121.
The replace in CommunitySource.availableDatasets() that always included
a trailing slash failed to consider "top-level" community datasets (e.g.
repoName.json instead of repoName_datasetName.json).
Although availableNarratives() was doing it right, switch it to using
the same removal function for consistency.
I considered changing the replace pattern to a regexp anchored at the
end with (/|$), but this requires escaping/quoting regexp metachars in
repoName and it turns out there is no handy function to do that.  It'd
be simple in other regexp flavors with interpolation and \Q and \E, but
having to add a quote function plus having to construct the regexp with
string concatenation made for something that seemed less clear than
doing startsWith() + slice() in a method.

charon: Fix duplicated repo name in getAvailable response for /community

---

src/sources/s3.js

Prevents deserializing potentially unsafe data types from user input.
yaml-front-matter uses js-yaml 3.x, which is unsafe by default, hence
the "safe" mode.  js-yaml 4.x is safe by default, but not used here.
---
I plan to merge and deploy this as soon as it passes CI.

sources: Load YAML frontmatter for groups-overview.md safely

---

src/app.js

Matches the new schema ids in Augur, see <https://github.com/nextstrain/augur/pull/852>.
I checked the new redirects work (if I munge the URL to `s{master}{trs/schemas/sidecars}`).

Add redirects for new schemas

---

docs/api-restful.rst
scripts/collect-datasets.js
scripts/collect-search-results.js
src/app.js
src/endpoints/sources.js
src/sources/models.js
src/utils/index.js

Adds "measurements" as a subresource type & sidecar file.
I searched for "tip-frequencies" within the repo and added "measurements" to the appropriate places.

Measurements sidecar

---

static-site/content/SARS-CoV-2-Datasets.yaml

Update the https://nextstrain.org/sars-cov-2/ map to link out to the country-level analyses at https://nextstrain.org/groups/africa-cdc. 
Mostly following steps from: https://docs.nextstrain.org/en/latest/guides/share/sars-cov-2.html
Check links. Let me know if we're allowed to have duplicate dataset entries for the same location or if I need unique geo IDs.
Example:
```
- url: https://nextstrain.org/groups/SC2ZamPub/ncov/africa/zambia
name: Zambia
geo: zambia
level: country
coords:
- 30
- -15
org:
name: Zambia Genomic Sequencing Consortium
url: https://nextstrain.org/groups/SC2ZamPub
```
and 
```
- url: https://nextstrain.org/groups/africa-cdc/ncov/zambia?c=clade_membership&f_country=Zambia&p=grid&tl=country
name: Zambia
geo: zambia
level: country
coords:
- 27.5599164      #<= pulled …
```

add: links to africa cdc pgi builds

---

src/authn/index.js

Rather than perpetually updating it on-the-fly with every request.
Resolves a downside of "authn: Upgrade existing sessions which pre-date
addition of authzRoles" (272ed09) and was simpler to implement than I
thought!
Related to #479 and #452.
I tested locally (which uses a file-based session store) by first acquiring an "old" session (i.e. logging in on an earlier version of the codebase), which contained a user object like:
```console
$ jq '.passport.user | fromjson' sessions/lMG7Ra3e79V5LuefCy2ObeMzucT4q5u6.json  
{
"username": "trs",
"groups": [
"test/owners",
"blab-private",
"seattleflu",
"trs-test/owners",
"test-private/editors",
"blab",
"inrb-drc"
]
}
```
then I restarted my local server with the code in this PR and made another request, after which my session contained the …

authn: Resave an on-the-fly updated user object back to the stored session

---

static-site/src/sections/sars-cov-2-page.jsx

Added a link to the clade-sampled reference tree onto https://nextstrain.org/sars-cov-2/
Related to https://github.com/nextstrain/ncov/pull/867
Could build locally and test. I ran a local build on a MacOS using the steps below: 
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
nvm install 16    # install node v16
nvm use 16
npm ci
cd nextstrain.org
git checkout add_note
npm run build
npm run server
```
Open http://localhost:5000/sars-cov-2/

add: reference link in paragraph

---

aws/iam/policy/NextstrainDotOrgServerInstance.json
aws/iam/policy/NextstrainDotOrgServerInstanceDev.json
package-lock.json
package.json
scripts/migrate-group

Does the "easy" stuff itself, preps the rest for performing manually and spits out a checklist.  Deleting IAM resources is a bear via the AWS API but easy via the AWS Console.  The two stage migration of steps before deploy and after deploy ensure that nextstrain.org can always "see" the Groups' data.  Removing the IAM group before copying the data helps avoid accidental changes in the midst of copying (although that also seems unlikely).  
I've tested this with the `test` and `test-private` Groups, but it'd also be good to test with a Group that's more "real". After merge, I'll test the whole process with `blab-private` and then `blab`.

Semi-automate migration of a Group from a single-tenant to multi-tenant bucket

---

docs/infrastructure.md
package-lock.json
package.json
src/app.js
src/authn/bearer.js
src/authn/index.js
src/middleware.js

Implements #485 and #492.
The former was mostly done on the Heroku side, but is described in updated doc here in https://github.com/nextstrain/nextstrain.org/commit/2e78f0f9123552f5bda1c363d6f99c73cdb9f666.
The latter is https://github.com/nextstrain/nextstrain.org/commit/9ed028ce3214e1d795e24e958c9d5654d1f3b5f3 which makes use of the more general groundwork laid in the earlier commits.

Canary deploys and user flag for auto-redirection

---

src/authn/index.js

Fixes "authn: Share our session cookie across nextstrain.org and
subdomains" (6be074e) for sessions which have a stored "cookie.expires"
property in the past.
Such sessions were receiving HTTP 500 errors because the manual
session.save() added by that commit caused connect-redis to recalculate
the Redis key TTL based on "session.cookie.expires - now" which
evaluated to an invalid negative value.  express-session always touches
the session, updating its cookie.expires (in our case based on the
maxAge value we configure), before the implicit save at the end of the
request (if a save will happen).  Do the same when we manually re-save.
Sessions are able to get a cookie.expires that's in the past because we
configure express-session with {rolling: true, resave: false}.  This
means the cookie …

authn: Touch sessions after setting cookie.domain and before manually re-saving

---

src/app.js

Including this allows posting nextclade reference trees to https://nextstrain.org/nextclade/sars-cov-2, etc...

Include "nextclade" as top-level path for Auspice

---

static-site/content/community-datasets.yaml

Dear Nextstrain team,
I sent a comment on behalf of Professor Jin-Won Song from the Republic of Korea (ROK).
I am a researcher at Korea University in the ROK. 
I am pleased to inform you that our analysis for interested viruses using nextstrain workflow (system) is finished. 
We hope that our dataset is accessible via a front web page (Nextstrain community page).
We want to replace the database of the hantavirus, influenzavirus, SFTSV that was posted previously.
I provided the URL submitted to Github.
I would appreciate it if you could post our dataset on the front page (or community page) in the Nextstrain web page.
Please let me know the due date of the process for posting our datasets and give me a reply if you have any questions.
What is the goal of this pull request? What does this …

community: Update Korea University dataset URLs and titles

---

.github/workflows/update-dataset-listings.yml
.github/workflows/update-search.yml

Resolves issues with system Python described in
<https://github.com/nextstrain/cli/issues/171>, but also makes future
maintenance easier by standardizing and centralizing how `nextstrain` is
installed.
Before merging:

Switch Nextstrain CLI setup in the GitHub Actions workflows to our new shared action

---

.github/workflows/ci.yml

Restores auto-deploy of master to the canary app since Heroku (as of
today) still doesn't have an ETA for restoration of their GitHub
integration.¹
¹ https://status.heroku.com/incidents/2413

Deploy to Heroku from CI after tests

---

README.md
docs/infrastructure.md

Should have been part of "Replace Travis CI with GitHub Actions"
(2ad1add), but we all forgot. ¯\_(ツ)_/¯
Related to #521.

Update references from Travis CI → GitHub Actions

---

src/app.js
src/authn/bearer.js
test/auspice_client_requests.json

The intent was for AuthzDenied errors to be translated to 401 Unauthorized and 403 Forbidden responses depending on the context, but this distinction was accidentally lost in "Handle authz failures in the app-wide error handler" (https://github.com/nextstrain/nextstrain.org/commit/fe2e5bd1bb3e5c8a5832692d384fbfdd918b70c7).  What were throws became assignments to "err" without corresponding changes to keep the control flow the same.
Also includes a small authn simplification I noticed while confirming some details of the 401 responses.
On prod:
```
$ curl -sI https://nextstrain.org/groups/nextflu-private/ | head -n1
HTTP/1.1 403 Forbidden
$ curl -sI https://nextstrain.org/groups/nextflu-private/ -H "Authorization: Bearer $(ini ~/.nextstrain/secrets authn id_token)" | head -n1
HTTP/1.1 403 …
```

Unauthorized vs. Forbidden error responses

---

src/authn/index.js

See individual commits for details. The primary goal here is to make session deserialization issues less fatal so that a) bugs we introduce don't have as much of an impact on users (e.g. they can still use public resources without having to wipe cookies or switch browsers) and that b) older versions of this codebase can co-exist with sessions created by newer versions. This last point is important, as I want to retain the ability to rollback from session-changing deploys gone wrong without new sessions poisoning the rollback.
To that end, I will rebase #537 on top of this and re-push it. My plan is then to deploy this first and then deploy #537.
- Manually tested various deserialization error states (missing keys hitting the new asserts, not JSON at all, etc).
- Logged in and out via …

Gracefully handle session deserialization errors

---

scripts/provision-group

They have to match for this code to work, so deriving the region makes
most sense here and avoids problems with mismatched regions or missing
regions from ambient AWS config/env.

provision-group: Set client region based on the Cognito User Pool

---

README.md

- There is not much need to highlight the work on SARS-CoV-2 here. A shorter blurb should suffice.
- We no longer maintain https://github.com/orgs/nextstrain/projects/5. There is a new project https://github.com/orgs/nextstrain/projects/11/views/5, but it is mostly intended for internal usage. I think the easiest thing here is to remove the current reference.
_N/A_
_N/A_

Update contributing blurb

---

docs/index.rst
docs/infrastructure.md
docs/sessions.rst
jest.config.js
package-lock.json
package.json
src/authn/index.js
src/authn/session.js
src/cryptography.js
src/endpoints/sources.js
src/exceptions.js
src/redis.js
src/user.js
test/authn.test.js
test/cryptography.test.js

Implements a system (in two parts) for keeping user information in sessions up-to-date and fresh, as I described in https://github.com/nextstrain/nextstrain.org/issues/81#issuecomment-1051420579.
This will enable us to implement group member management endpoints in the RESTful API and have the user data be consistent.
See commit messages for full details.
Fixes #81.
Incorporates #535.
For the session change, I tested the following scenarios locally:
- New login
- No renewal required
- Successful renewal
- Failed renewal
Outcome: user logged out but session preserved.  May be redirected to login page if req is for private resource.  If last login was recent enough, IdP may remember and issue new login automatically.
- Other failure (bug, service issue, network issue, etc.)
Outcome: sparse …

Refresh user info

---

package-lock.json
package.json

We no longer need my fork patched with the change in my upstream PR¹,
since the latter was merged and released back in January as part of
upstream version 10.0.0.
¹ https://github.com/npm/make-fetch-happen/pull/65
Follows up on a commit from https://github.com/nextstrain/nextstrain.org/pull/443.

dev: Switch back to upstream releases of make-fetch-happen

---

server.js

This can be expected to show for anyone using macOS >=12 [where AirPlay Receiver uses port 5000 by default][1]. However, the old lsof command truncates the command name:
```
% lsof -n -i :5000 | grep LISTEN
ControlCe 687 vlin   16u  IPv4 0x80682f2dbd9b4293      0t0  TCP *:commplex-main (LISTEN)
ControlCe 687 vlin   17u  IPv6 0x80682f242196ef0b      0t0  TCP *:commplex-main (LISTEN)
```
Adding `+c0` shows the full name:
```
% lsof +c0 -n -i :5000 | grep LISTEN
ControlCenter                687 vlin   16u  IPv4 0x80682f2dbd9b4293      0t0  TCP *:commplex-main (LISTEN)
ControlCenter                687 vlin   17u  IPv6 0x80682f242196ef0b      0t0  TCP *:commplex-main (LISTEN)
```
which can then be used in an internet query for "why is ControlCenter listening on port 5000?"
[1]: …

Show full command name in note to use lsof

---

src/sources/core.js
src/sources/models.js

It seems that ostensibly the main reason for going through CloudFront
for requests from the nextstrain.org server → S3¹ is that it's cheaper
(and maybe faster).
While this is true for requests from the internet, our Heroku dynos run
on AWS EC2 in us-east-1 (the same region as our S3 buckets) and thus are
(AFAIK) treated as free internal requests for the purposes of pricing.
I don't believe CloudFront marks down data egress back into AWS
separately from other egress like S3, and CloudFront also has more
expensive per-request pricing than S3, esp. for our most common requests
(GET).  That said, CloudFront has higher free tier quotas for both
bandwidth and requests, so it's hard to know the net balance of the two
services without our request/egress numbers for S3 ⟷ Heroku (which we
don't …

sources: Bypass CloudFront for core and staging source S3 buckets

---

aws/iam/policy/NextstrainDotOrgServerInstanceDev.json
scripts/migrate-group
scripts/migrate-groups-layout
src/sources/groups.js
src/utils/scripts.js

The gist here is a behind-the-scenes layout change for the `nextstrain-groups` bucket to better separate objects within a group.
Currently:
```
nextstrain-groups/
some-name/
a_b.json
x_y_z.json
blah.md
group-overview.md
```
With this:
```
nextstrain-groups/
some-name/
datasets/
a_b.json
x_y_z.json
narratives/
blah.md
group-overview.md
```
This has been in the back of my mind for a while, but was recently reinvigorated/remotivated by discussion of issues with the current layout when describing https://github.com/nextstrain/nextstrain.org/issues/547.
See commit messages for full details.
Related to #478.
_to perform in order_

Adjust layout of multi-tenant groups bucket

---

.github/workflows/ci.yml
package-lock.json
package.json
src/app.js
src/endpoints/charon/getAvailable.js
src/endpoints/charon/getDataset.js
src/endpoints/charon/getNarrative.js
src/endpoints/charon/getSourceInfo.js
src/endpoints/charon/index.js
src/endpoints/sources.js
src/exceptions.js
src/sources/community.js
src/sources/core.js
src/sources/models.js
src/utils/prefix.js
test/auspice_client_requests.json
test/auspice_client_requests.test.js

Several related changes, all detailed in commit messages, but the top-line change is a consolidation of code paths between our Charon endpoints' handlers and the new "sources" handlers powering the RESTful API endpoints.
Resolves #150.

charon: Use new "sources" handlers for getDataset, getNarrative, and getSourceInfo requests

---

.github/dependabot.yml

_(same thing as nextstrain/auspice.us#32 but for this repo)_
Uses dependabot to check for auspice updates.
- #421
- To fully close this issue, we would need a GitHub Actions workflow to auto-merge these PRs ([I've done this with serratus.io](https://github.com/serratus-bio/serratus.io/blob/2ad2a2dba2b0a8ac90bb5634d0afec5b4aa7bfbe/.github/workflows/dependabot-auto-merge.yml)).
- Note that there's also a nice log for these checks: https://github.com/victorlin/nextstrain.org/network/updates

Check for auspice updates daily

---

package-lock.json
package.json
src/app.js
src/async.js
src/endpoints/sources.js

Fixes sporadic 503s (from Heroku's routing layer) and 404s (from us) on requests that should have been 304s. First noticed on /charon/getDataset requests after the deploy of #557, but present for longer on other endpoints.
See commit messages (and the linked notes + Slack thread within) for all the details.

Fix mixed up 503s and 404s for what should be successful responses

---

server.js
src/app.js
src/endpoints/sources.js

Resolve 503s from Heroku's routing layer

---

src/sources/models.js

…as the lowest priority media type (i.e. we'll use it grudgingly).
This media type is the only one used by the media.githubusercontent.com
endpoint which provides access to objects in Git LFS for Community on
GitHub datasets.
Resolves <https://github.com/nextstrain/nextstrain.org/issues/575>.

sources: Accept application/octet-stream for dataset JSONs

---

docs/conf.py
docs/requirements.txt

The new extension has sphinx_copybutton pre-installed and configured. This change enables it here.
This also makes it easier to configure other extensions across multiple docs projects.
https://github.com/nextstrain/sphinx-theme/issues/30

docs: Install nextstrain.sphinx.theme extension

---

src/app.js
src/endpoints/cli.js
src/endpoints/index.js

This is makes it much easier to do without knowing the actual version of
the latest release, as the asset names contain the version (as is
proper).  I expect the endpoint to be used by short standalone installer
scripts¹ and other automation which would benefit from using the
standalone installation archives, e.g. by fetching one of:
https://nextstrain.org/cli/download/latest/standalone-x86_64-unknown-linux-gnu.tar.gz
https://nextstrain.org/cli/download/latest/standalone-x86_64-apple-darwin.tar.gz
https://nextstrain.org/cli/download/latest/standalone-x86_64-pc-windows-msvc.zip
Going through a nextstrain.org endpoint instead of using GitHub's API
directly also provides such automation an increase in future
compatibility potential since nextstrain.org can act as a
translation/insulation …

Add endpoint for downloading Nextstrain CLI assets from its latest release

---

package.json

This alias has been around since 84a45a8bb9b1a8c967b33ab6964ab24c793084ad and should be unused at this point.
_N/A_

Remove `set-up` → `build` npm command alias

---

docs/authz.rst
package-lock.json
package.json
src/app.js
src/authz/index.js
src/authz/tags.js
src/endpoints/groups.js
src/endpoints/index.js
src/endpoints/sources.js
src/endpoints/users.js
src/groups.js
src/metaSources.js
src/upstream.js

Adds RESTful API endpoints for downloading/uploading/removing group overviews and logos.
- Closes #547
- 34f02d57e29d99d2725fa7bb2dc20a2a8ee49866 from https://github.com/nextstrain/nextstrain.org/pull/570#discussion_r960106390
Automated:
Manual:
<details>
<summary>
Local testing from a member of `test-private/owners`. [Maybe automate?](https://github.com/nextstrain/nextstrain.org/pull/570#discussion_r923922221)
</summary>
Token setup
```sh
nextstrain login
id_token_line=$(grep id_token ~/.nextstrain/secrets)
token=${id_token_line#"id_token = "}
```
GET private overview works
```sh
curl http://localhost:5000/groups/test-private/settings/overview \
--header "Authorization: Bearer $token" \
--header 'Accept: text/markdown' \
--compressed \
| tee overview.md
```
DELETE private overview works …

Add RESTful API endpoints for Groups customizations

---

.github/workflows/ci.yml

Same reasoning as @tsibley in https://github.com/nextstrain/cli/commit/fab709a2f45fc74afe2a15038e877e4dd58ae222:
Running on push _and_ PRs is often redundant.  For PRs, we really care about the putative merge of the PR branch, and that's what "on: pull_request" tests.  We typically do not need push-level CI results for PRs.  On the other hand, CI results for every push to master are nice to have both as a safety backstop and for the linear chain of CI history it produces (e.g. to debug the impact of external changes on our CI).
The primary downside I see is that you can no longer push without opening a PR just to see what CI says, but I think that's an acceptable tradeoff, especially now that draft PRs are a thing.  To mitigate this downside, "on: workflow_dispatch" allows CI to be …

dev: Trim back the overgrown CI jobs

---

.eslintignore
src/sources/fetch.js
src/sources/models.js
test/auspice_client_requests.json
test/requests.test.js

Underscores worked because of an implementation detail about how we're backing those files that is leaking through.  The presence of underscores breaks many assumptions made by nextstrain.org and Auspice, a minor example of which is Auspice's dataset selector.  Other broken assumptions could lead to more serious breakage, such "confused deputy" problems resulting in authz bugs (though I don't think this is the case currently).
Note that /fetch/… paths are allowed to contain underscores, as these are resolved to external resources.
Resolves <https://github.com/nextstrain/nextstrain.org/issues/432>.
Related to <https://github.com/nextstrain/nextstrain.org/pull/517>.

Forbid underscores in resource (dataset, narrative) paths

---

.github/workflows/ci.yml
.github/workflows/remind-to-promote.yml
package-lock.json
package.json
scripts/provision-group.js
scripts/remind-to-promote
scripts/remind-to-promote.js

…if we're tardy about it.
- Generated a [`read-protected` scoped](https://devcenter.heroku.com/articles/oauth#scopes) Heroku API token for our Heroku bot user
- Added the token as a `HEROKU_TOKEN_READ_PROTECTED` GitHub org-level secret for Actions
- Created a ["Nextstrain Bot" Slack app](https://api.slack.com/apps/A047F02PTE2) and ["installed" it into our Slack org](https://bedfordlab.slack.com/apps/A047F02PTE2-nextstrain-bot) in order to generate [a suitable bot token](https://api.slack.com/apps/A047F02PTE2/oauth?).
- Added the bot token as a `SLACK_TOKEN` GitHub org-level secret for Actions

Remind us to promote the canary to production

---

scripts/collect-search-results.js

Replace all instances of underscore in the filename to create the URL. Never noticed this issue before, but now the underscores in the URLs lead to a BadRequest error since we explicitly forbid underscores in the resource path in #611.
Tested locally for both SARS-CoV-2 and seasonal flu.

scripts/collect-search-results: Update `fileToUrl`

---

.github/workflows/remind-to-promote.yml

We saw duplicate reminders last night in #nextstrain-dev.  The culprit was a misunderstanding (by me) of how updates work with the GitHub Actions cache.  The result was the cache wasn't being updated¹, meaning every run thought it hadn't sent a reminder already.
¹ e.g. <https://github.com/nextstrain/nextstrain.org/actions/runs/3382926547/jobs/5618339152#step:16:2>
Related to #615.

dev: Fix the remind-to-promote workflow so new state is actually saved

---

scripts/migrate-group.js

…even if they match *.json or *.md.  Instead, report them as unsynced files.
This correctly handles an observed case of an object named "archive/zika.json" that was dutifully copied over, though it would be inaccessible.
Related-to: <https://github.com/nextstrain/private/issues/66>

migrate-group: Exclude S3 object keys containing "/" from syncing

---

auspice-client/customisations/languageSelector.js
auspice-client/customisations/navbar.js
auspice-client/customisations/splash.js

This is necessary for Webpack 5, which resolves paths as fully specified.
Something similar was done in the CJS→ESM migration (56b50c572d043fe296562b08ec7027bcc067260d), independent of `auspice-client`.
For https://github.com/nextstrain/auspice/pull/1520 to work with nextstrain.org.

auspice-client: Append extension on ESM imports

---

package-lock.json
package.json
src/app.js
src/endpoints/cli.js
src/httpErrors.js

This new endpoint allows the standalone installer to install not just
released versions but also the builds produced by arbitrary CI runs.
That's very helpful for development and testing of PRs.  With this new
endpoint, for example, we can run:
curl -fsSL --proto '=https' https://nextstrain.org/cli/installer/linux \
| DESTINATION=/tmp/cli bash -s ci-build/3859193828
to install /tmp/cli/nextstrain from:
https://github.com/nextstrain/cli/actions/runs/3859193828#artifacts
Artifacts from GitHub Actions workflow runs require a bit more ceremony
than release assets, as all artifacts come wrapped in a ZIP file, which
we need to unwrap server-side for our installer.  Doing this server-side
also resolves the issue of artifacts requiring authentication to
download (despite that our artifacts are …

Support downloading standalone installation archives from CI builds

---

src/app.js
src/endpoints/cli.js

This new endpoint allows the standalone installer to install not just released versions but also the CI builds produced for arbitrary PRs. That's very helpful for development and testing of PRs.  With this new endpoint, for example, we can run:
curl -fsSL --proto '=https' https://nextstrain.org/cli/installer/linux \
| DESTINATION=/tmp/cli bash -s pr-build/243
to install /tmp/cli/nextstrain from the last successful CI build for:
https://github.com/nextstrain/cli/pulls/243
This uses existing support for downloading archives from CI builds.  The PR id is translated into the latest successful CI run id for that PR.
#643

endpoints/cli: Support downloading standalone installation archives from PR builds

---

src/endpoints/charon/setAvailableDatasets.js

This usage was missed by "sources: Bypass CloudFront for core and staging source S3 buckets" (4365b26).  The rationale for that commit applies here as well.
Related-to: <https://github.com/nextstrain/nextstrain.org/pull/552>

sources: Bypass CloudFront for core and staging source manifests

---

aws/iam/main.tf
aws/iam/variable-env.tf
docs/terraform.rst
env/production/terraform.tf
env/testing/terraform.tf

The "dev" policy becomes a general "non-production" policy, and we'll be able to use Terraform templating to tailor the policies to specific environments.  This will be necessary for Cognito access soon.
#656

aws/iam: Manage IAM resources for the testing environment

---

src/app.js
src/endpoints/cli.js
src/middleware.js
src/sources/community.js

This makes it possible, for example, to do client-side analyses on the dataset JSONs using standard nextstrain.org URLs.  Requested by @corneliusroemer¹, as it makes it much easier to load arbitrary trees into Nextclade web.
It's also nice in principle to allow cross-origin requests for public resources since it enables unforeseen integrations without having to ask permission.
I didn't use the "cors" library here since it does a lot more than what we need, is more permissive by default, and setting our own headers is less of a blackbox and thus clearer as to what we're sending and when.
¹ <https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1666027479770509>
<https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1676473418174269>

Allow read-only CORS requests for public resources

---

src/sources/community.js

This partially reverts «Remove an extra layer of CORS-unfriendly indirection from "raw" GitHub URLs» (d5ad654b) by switching this source's base URL back to github.com instead of
raw.githubusercontent.com.
It's important to go thru github.com and let it redirect us to the final location because GitHub serves LFS blobs on a different final domain, media.githubusercontent.com.
Related-to: <https://github.com/nextstrain/nextstrain.org/pull/658>
Related-to: <https://support.nextstrain.org/agent/nextstrain/nextstrain/tickets/details/668036000003625001>

sources/community: Restore support for datasets/narratives stored with Git LFS

---

src/endpoints/static.js

Prior to this commit, I was unable to load any individual Group page
after starting the dev server with `npm run dev`. I would get the error:
```
TypeError: (intermediate value).createProxyServer is not a function
```
Since `http-proxy` only has a default export¹, so we must access
the `default` property of the module in order to access
the `createProxyServer` method.
¹ https://github.com/http-party/node-http-proxy/blob/master/index.js#L13
Follow up of #583

Fix Gatsby proxy for dev

---

.github/workflows/dependabot-automation.yml

The auto-merge is reasonable because the target branch is deployed to the canary site (next.nextstrain.org), not the production site. Auto-merge allows us to test the latest Auspice release on the canary site without manually merging the automatically created version bump PRs.
Prompted by [Slack discussion](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1679447507855999).

Add workflow to auto-merge Auspice bump PRs

---

.github/dependabot.yml
README.md
auspice-client/.gitignore
auspice-client/package-lock.json
auspice-client/package.json
build.sh
package-lock.json
package.json
src/endpoints/charon/getDataset.js
src/utils/datasetConverters.js

https://github.com/nextstrain/auspice/pull/1661

Move Auspice dep from the server code to the auspice-client customizations

---

docs/infrastructure.md
env/production/groups.json
env/testing/groups.json
scripts/migrate-group.js
scripts/provision-group.js
src/config.js
src/endpoints/users.js
src/groups.js
test/auspice_client_requests.json

These environments do not share the resources behind group—they have separate Cognito user pools and a shared but access-partitioned S3 bucket—so it doesn't make that much sense to bundle both into the same data file anymore.  Pragmatically, this also avoids a bunch of noisy errors at local dev server start and periodically thereafter.

Split groups data between production and testing environments

---

static-site/src/sections/sars-cov-2-page.jsx

This commit makes a few small changes to the SARS-CoV-2 resources listing:
- Adds a link to `/sars-cov-2/forecasts`
- Updates abstract text
- Removes link to `/groups/blab/sars-like-cov` (less relevant three years in)
- Removes link to discussion.nextstrain.org (links to discussion forum are now much more prominent in docs pages)
Tested locally and via Heroku review App.

SC2: update resources listing

---

server.js

The inherently dynamic require() was changed to a static import in the conversion to ES modules¹ with "Use cjs-to-es6 to help conversion" (1963fcd).  That broke the intended delayed import, since Node.js starts locating and executing static imports before the actual import statements are reached in the importing module's execution.  Use a dynamic import() instead to restore the delayed import.
We delay the import until after setting global.verbose so that calls to utils.verbose() in the codebase respect the server's --verbose option as expected.
The missing utils.verbose() output this caused was first noticed by @jameshadfield.²
¹ <https://github.com/nextstrain/nextstrain.org/pull/583>
² In <https://github.com/nextstrain/nextstrain.org/pull/678> as …

Restore delayed import of ./src/app.js by using a dynamic import()

---

data/manifest_core.json
data/manifest_staging.json
src/endpoints/charon/setAvailableDatasets.js

The manifest files are a continual point of confusion, and part of the
reason may be their location on S3. Bringing them into source code has
benefits for visibility/understanding, ease of tracking changes,
and should help with their eventual removal.
Historically, these were part of Auspice's source code and were extracted
into their own files in order to allow other groups to more easily use
Auspice. As nextstrain.org is not intended for external use there is no
problem bringing them back into source code.
Manifests taken 2023-04-17 at ~11h00 (NZ time) using
```
curl --compressed "https://nextstrain-data.s3.amazonaws.com/manifest_guest.json" --output data/manifest_core.json
curl --compressed "https://nextstrain-staging.s3.amazonaws.com/manifest_guest.json" --output …
```

Move manifest.json files into source code

---

data/manifest_core.json

This updates `manifest_core.json` with the newly implemented 21L datasets like [nextstrain.org/ncov/gisaid/21L/global/6m](https://nextstrain.org/ncov/gisaid/21L/global/6m).
Tested via review app. Everything looks to be working.

Update manifest with 21L ncov datasets

---

src/app.js
src/async.js
src/endpoints/groups.js
static-site/gatsby-node.js
static-site/src/components/Datasets/situation-reports-by-language.jsx
static-site/src/components/Groups/edit-logo-form.jsx
static-site/src/components/Groups/edit-overview-form.jsx
static-site/src/components/Groups/styles.jsx
static-site/src/components/splash/errorMessages.jsx
static-site/src/components/splash/sourceInfoHeading.jsx
static-site/src/layouts/generalComponents.jsx
static-site/src/pages/groups.jsx
static-site/src/sections/group-settings-page.jsx
static-site/src/sections/individual-group-page.jsx
static-site/src/sections/influenza-page.jsx
static-site/src/sections/pathogens.jsx
static-site/src/sections/sequence-search.jsx
static-site/src/sections/staging-page.jsx

Adds a new page for users to edit group customizations, which currently only include the logo and overview.
Includes a new OPTIONS route to check if users are authorized to edit group settings. 
Only users with the `owner` role should see the button "EDIT GROUP SETTINGS" to navigate to the new page:
Other users can still navigate to the new page using the URL `/groups/:groupName/settings`, but they would only see an error banner:
The new page allows users to:
- delete current logo
- upload new logo
- edit/upload overview

Add page to edit group customizations

---

src/app.js
src/endpoints/cli.js
src/templateLiterals.js
static-site/src/components/Groups/edit-logo-form.jsx
static-site/src/components/Groups/edit-overview-form.jsx
static-site/src/sections/group-settings-page.jsx
static-site/src/sections/individual-group-page.jsx

Avoids having to write out encodeURIComponent(), which is quite a mouthful!

Use "href" template literals for safe-by-construction URL strings

---

static-site/src/sections/sars-cov-2-forecasts-page.jsx

This commit switches from the currently PNG screenshots to a live iFrame embedding from https://nextstrain.github.io/forecasts-ncov/. This allows higher resolution and permits interactivity. I believe this is especially welcome for the lineage barchart where mousing over individual values is very helpful.
The iFrame width is responsive, but there is not perfect control over its height. That said, I believe my max(580px, 72%) solution works well at a variety of window sizes from vertical mobile to landscape desktop.
I also got rid of the disclaimer at the top of the page. This sort of MLR model is very standard at this point. It's used in the CDC Variant Tracker and we've spent a lot of time validating retrospective MLR frequency hindcasts, nowcasts and forecasts and I'm very happy with …

Swap to iFrame for SARS-CoV-2 forecasts page

---

package-lock.json
package.json

Its last direct use was removed by "Remove dataset listing /influenza, /staging" (a75539a) and "Remove updates to strain-search JSON" (86956ef).¹
Related-to: <https://github.com/nextstrain/nextstrain.org/pull/694>

Remove p-limit from our direct dependencies

---

.readthedocs.yml

Read the Docs will soon require the specification of a build OS in our configuration file [1] and have already started temporary enforcement of this requirement as a warning.
[1] https://blog.readthedocs.com/use-build-os-config/

Specify Read the Docs build OS

---

data/manifest_core.json
src/app.js
src/redirects.js
static-site/src/components/Cards/coreCards.js
static-site/src/components/Cards/pathogenCards.js

All 3 current /mpox datasets (/mpox/lineage-B.1, /mpox/clade-IIb, /mpox/all-clades) are added to the manifest (and thus Auspice's dropdowns), with the last one set as the default. The card on the main splash page is switched to /mpox.
Context (slack): <https://bedfordlab.slack.com/archives/C03G8HQEV18/p1695508115055009>
The original /monkeypox/* URLs are left unchanged however we can remove these and add redirects instead if we wish to. Steps to do so:
* Removing `monkeypox` from the (committed) manifest JSON will remove it from the auspice sidebar dropdowns and stop the ability for default URL redirects such as 'monkeypox' → 'monkeypox/hmpxv1'
* Removing `/monkeypox` from `app.js` will stop nextstrain.org/monkeypox URLs working at all (they'll 404)
* Redirects to go from /monkeypox URLs …

Add mpox as the default monkeypox URL prefix

---

src/redirects.js

See https://bedfordlab.slack.com/archives/C03G8HQEV18/p1695669073962029?thread_ts=1695508115.055009&cid=C03G8HQEV18

Redirect `/monkeypox` to `/mpox`

---

static-site/README.md

Part of my efforts to get on-boarding docs in place for new hires joining the Bedford lab. 
I could not find any docs on how to add new members to the team page. I also had to follow through a linked GitHub commit¹ to figure out how the footer in docs.nextstrain.org was updated the last time we updated the team page² so adding those instructions here as well.
¹ https://github.com/nextstrain/sphinx-theme/commit/65487653771efbcfa19dbcf2adab19a90dd85318 
² https://github.com/nextstrain/nextstrain.org/pull/640

static-site/README: add docs on how to add new team member

---

aws/iam/main.tf
aws/iam/policy/NextstrainDotOrgServerInstance-testing.tftpl.json
aws/iam/policy/NextstrainDotOrgServerInstance.tftpl.json
aws/iam/variable-COGNITO_USER_POOL_ID.tf
aws/variable-COGNITO_USER_POOL_ID.tf
docs/api-restful.rst
env/production/terraform.tf
env/testing/terraform.tf
src/app.js
src/cognito.js
src/endpoints/groups.js
src/groups.js
src/utils/iterators.js
static-site/src/sections/individual-group-page.jsx

Adds RESTful API endpoints for listing/adding/removing existing users to group membership roles.
Things to address later:
Given these conflicting constraints, a separate dev-only user pool seems most appropriate, but that's a bit more initial work to setup and more ongoing work to manage/keep relevant over time.  I'm a little loathe to address that now or as a prerequisite for this work, but I also don't like not having a dev/testing story here.
We're rapidly reaching (or are at?) the point where I really want separate dev vs. prod AWS accounts controlled by Terraform or CloudFormation something.

Add RESTful API for managing Groups members

---

.github/workflows/ci.yml

We'd been assuming builds on Heroku were always successful, which meant the GitHub Actions status could (and did) mask build issues on Heroku.
Resolves <https://github.com/nextstrain/nextstrain.org/issues/726>.

dev: Check the Heroku build status during our GitHub Actions deploy job

---

aws/cognito/outputs.tf
docs/infrastructure.md
docs/terraform.rst
env/outputs.tf
env/production/config.json
env/testing/config.json
src/authn/index.js
src/config.js

OIDC is OpenID Connect 1.0, which is an identity/authentication protocol layered on top of OAuth 2.0's authorization protocol.  AWS Cognito implements OIDC/OAuth2 but our authn code hardcoded some assumptions about Cognito specifically.  Undo that and parameterize and generalize the code to work (in theory) with other OIDC identity providers (IdPs). In practice, some additional changes may be necessary for specific other IdPs, but as-is I can get this generalized authn code to work against a test Azure AD IdP.
Outside of authn, there are still some other bits of the codebase which require Cognito.  Those will be addressed in subsequent work.
This work is motivated by CDC AMD's efforts to host a copy of nextstrain.org internally in order to avail themselves of Groups internally. …

authn: Generalize support to ~any OIDC/OAuth2 IdP, not just AWS Cognito

---

docs/infrastructure.md
docs/production.rst
env/outputs.tf
env/production/config.json
src/aws.js
src/config.js

Make it explicit in our config, code, and documentation.
This became newly and implicitly necessary with the upgrade from the v2 to v3 SDK in b326340b.  I didn't notice in development, however, because region was implicitly sourced from the default profile in my personal AWS config file.  That config file isn't available in production, of course, and this resulted in some requests 500-ing with "region not set" errors upon deploy to Heroku.¹  I likely could have noticed had I tried the Heroku review app for the original changes.
Related-to: <https://github.com/nextstrain/nextstrain.org/pull/733>
¹ <https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1698343822747429>

Explicitly configure AWS region

---

static-site/src/sections/group-settings-page.jsx

Current implementation means an error for the settings page is shown in the console for every visit to a group page where you aren't logged in as an owner of the group.
It confused me until I realized that `canUserEditGroupSettings` is being called on the group page to determine whether to display the edit button. It seems like this is by design, and I'm not sure there is an easy way to achieve the same behavior without sending this call to /groups/{group}/settings. I think ok to leave as-is, but some extra context might be helpful for anyone who has a tendency to think that something is wrong when seeing red error messages in the browser console.
N/A

Add context to console error on groups page

---

test/authn.test.js

Ensures the condition under which we're testing behaviour rather than assuming the condition.
I noticed failures of that assumption recently, because I've started running with keys configured in local development to allow for session continuity across local server restarts.

tests: Ensure SESSION_ENCRYPTION_KEYS is unset rather than assume it isn't

---

src/authn/index.js
src/httpErrors.js

Fixes regression where after a failed Bearer authn attempt the request processing continued on (still unauthenticated).  Failed attempts now once again produce an error response (typically 400 or 401) with the appropriate challenge (if any) in the WWW-Authenticate header.  In particular, this restores responses like:
HTTP/1.1 401 Unauthorized
WWW-Authenticate: error="invalid_token" …
when a stale token is sent in the request.  Nextstrain CLI relies on these responses to form a more helpful error message to the user.
The regression was introduced by "authn: Switch to custom authenticator callbacks" (aca4d07f) because the Passport "strategy" we use here stops performing the default behaviour we were relying on once a callback is provided.  Instead, it expects the callback to provide all the …

authn: Stop request processing on failed Bearer authn attempts

---

data/manifest_core.json

The lassa repo¹ has a link to nextstrain.org/lassa that doesn't work. This should fix it.
¹ <https://github.com/nextstrain/lassa>

Add lassa build to manifest

---

src/s3.js

The default parameter values for this function would only be used in the case where no argument was provided, which makes no sense as a bucket and key will always be needed. These changes preserve the intended defaults of headers={} and method='GET'. (Reading the previous code it seems the intention was to allow a default method of 'GET', despite the docstring indicating it was required.)

[bugfix] default params for signedUrl()

---

data/manifest_core.json

Per user request, update dengue builds to include E genes as well as whole genome.
* https://github.com/nextstrain/dengue/issues/17

Update manifest with dengue gene datasets

---

static-site/src/pages/whoami.jsx

This reverts #769, which shows all public groups instead of just public group memberships as intended.
Will re-implement in another PR.

Revert "whoami: List public group memberships…"

---

aws/cognito/clients.tf

In practice, 30 days seems too short.
I've observed users who get the CLI installed and logged in but then don't get to uploading their datasets until more than 30 days later (i.e. they spend time producing the datasets or on other work) and so then have to log in again when it's time to upload.  This has been a minor frustration and stumbling block for them.
In a different use case, @corneliusroemer has also found 30 days to be too short in automation contexts.  Although I'd suggest a different approach for automation¹, I suspect his approach will not be an uncommon one for users to take so we should ensure it's not too onerous when they do.
Resolves <https://github.com/nextstrain/cli/issues/337>.
¹ <https://github.com/nextstrain/cli/issues/337#issuecomment-1883534419>

aws/cognito: Extend validity of the CLI's refresh tokens from 30 → 90 days

---

static-site/README.md

Closes <https://github.com/nextstrain/nextstrain.org/issues/597>. Will merge immediately as the only file changed is `static-site/README.md`

[static site] Add MacOS installation tips

---

src/upstream.js

This permits private caching (e.g. by browsers), like now, but instructs them to always check for updates (revalidate) before using the cached response (unlike now).  Prior to this, browsers would use their own heuristics to figure out when to revalidate which could lead to staleness and user confusion.
This new caching policy doesn't save a request/response cycle, but it does save response transfer time when a cached response can be used. It also forbids using the cached response when the browser is offline, though I'm not sure we care about that use case (and not sure other bits of nextstrain.org support it, like the Auspice client).
This affects the RESTful API and Charon API endpoints for datasets and narratives, as well as the endpoints for a group's overview and logo.
Resolves …

upstream: Add a Cache-Control header to resource responses

---

docs/resource-collection.rst
resourceIndexer/coreStagingS3.js
resourceIndexer/coreUrlRemapping.js
resourceIndexer/inventory.js
resourceIndexer/main.js
src/endpoints/charon/parseManifest.js
src/endpoints/charon/setAvailableDatasets.js
src/endpoints/sources.js
src/sources/models.js
test/date_descriptor.test.js
test/inventory_parsing.test.js

Closes #777. See that issue or the commit messages for full details.
The earliest nCoV dataset we have is from 2020-01-19, and was back then accessed via `/ncov`. Now `/ncov@2020-01-19` redirects to `/ncov/gisaid/global/6m@2020-01-19` and loads that dataset. 
We can access the `/dengue/denv1` datasets prior to Jan 2024 via either `/dengue/denv1@YYYY-MM-DD` or `/dengue/denv1/genome@YYYY-MM-DD`, with the former redirecting to the latter.
Best done locally, via something like
```bash
mkdir -p devData
node resourceIndexer/main.js --output devData/index.json --save-inventories \
--indent --resourceTypes dataset --collections core # needs AWS creds to access s3://nextstrain-inventories
RESOURCE_INDEX="devData/index.json" node server.js --verbose
```
The heroku review app will not correctly use …

Surface previous dataset versions across URL redirects

---

resourceIndexer/coreUrlRemapping.js
src/redirects.js
src/resourceIndex.js
test/date_descriptor.test.js

Recent work surfaced previous dataset versions across URL redirects¹ by
mirroring the dataset-name resolution process we use for requests on the
server. However it neglected to consider the redirects which are handled
prior to this in the server. This commit adds that functionality as
well. This situation was recently discussed in slack².
To use mpox as an example: the dataset (URL) path "mpox/all-clades" now includes previous versions which were named "monkeypox_mpxv.json", thus extending the snapshot history of this dataset from 2023-09-23 to 2022-06-12.
Our usage of `ncov_global.json` (similarly for other regions) is a lot more complex, because we didn't make clean dataset name switches like monkeypox/mpox.
Looking at the current live index (i.e. before this PR) the `ncov.json` dataset …

[resource indexer] include dataset redirects in index

---

src/endpoints/sources.js
src/routing/core.js
src/routing/setup.js
src/routing/staging.js
test/date_descriptor.test.js

Closes https://github.com/nextstrain/nextstrain.org/issues/792
Old behaviour: flu/seasonal/h3n2?c=cTiter → flu/seasonal/h3n2/h1/2y
New behaviour: flu/seasonal/h3n2?c=cTiter → flu/seasonal/h3n2/h1/2y?c=cTiter

Preserve URL queries across redirects

---

.github/workflows/ci.yml

It used to be that once the Heroku build log stream response completed, their API would return a build status of "succeeded".  Recently however it seems like now there's a delay between the log stream response completing and their API returning the up-to-date build status.  Build in a 60s buffer wait time to account for that.
Resolves <https://github.com/nextstrain/nextstrain.org/issues/794>.

dev: Wait up to 60s for the Heroku build status to change to "succeeded"

---

data/manifest_core.json

This pull request changes the default display for the avian-flu builds to be H5Nx, instead of H5N1. Avian influenza H5 epidemiology has changed in the past few years due to the expansion of clade 2.3.4.4, which now represents the major group of viruses circulating in the world. These viruses reassort frequently, and the HA was associated with N8, N2, and N6s prior to global expansion. H5Nx captures this history, while H5N1 does not. 
This pull request changes a single line in `manifest_core.json`

Changing the avian-flu default page from h5n1 to h5nx

---

.github/workflows/ci.yml

Organization variable was recently added in https://github.com/nextstrain/zika/pull/54.

CI: Use GitHub org variable for AWS region

---

.github/workflows/ci.yml

Previously, the unauthenticated requests were limited to [60 per hour per IP address](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api#primary-rate-limit-for-unauthenticated-users) which are likely shared by other jobs using the same GitHub-hosted runners.
Prompted by https://github.com/nextstrain/nextstrain.org/pull/810#discussion_r1556421873

CI: Use GitHub Actions token for higher rate limit

---

test/requests.test.js

https://github.com/nextstrain/zika/pull/57 removed the zika root sequence sidecar (as it's inlined in the main JSON). Note that the staging/zika dataset still has the root sequence sidecar and we assert its existence in tests here!

Update tests now that zika root sequence is inline

---

package.json

As someone who wants to routinely use the actual built static-site¹, it makes no sense to pay the time cost of `next build` every run of the test suite or restart of the dev server.  We already check that the built assets are available at server start, so if you forget you do get a reminder (in the form of an error).
¹ The hot-reloading static-site is great for working on the static-site
itself, but when working on the server-side routes, I'd rather have
higher fidelity with production.

dev: Unbundle `next build static-site` from `npm run test:ci` and `… dev:ssg`

---

src/upstream.js

For example, our RESTful endpoints perform content negotiation and use the result to determine Content-Type (and also what to Accept in the request to upstream), but our Charon endpoints do not set Content-Type at all.  Set it based on the upstream response in that situation.
I noticed this bug (while investigating another issue¹) because the automatic compression middleware wasn't applying to the /charon/getDataset endpoint due to the lack of Content-Type.
¹ <https://github.com/nextstrain/nextstrain.org/issues/832>

upstream: Forward Content-Type from upstream if we don't already have one

---

src/authn/index.js
src/endpoints/users.js

#780 broke /whoami for users that are members of old test Cognito groups. This is due to unhandled errors in the case that a Cognito group does not map to a valid group in groups.json. This PR addresses the issue.
- prompted by https://github.com/nextstrain/nextstrain.org/pull/780#discussion_r1578485451

Fix /whoami

---

package-lock.json
package.json
server.js
src/aws.js
src/groups.js
src/startupMessage.js
src/utils/index.js

Closes #685
@victorlin could you take a look at this, especially with how it may pertain to someone running the server as a groups app?

Improve server startup messages

---

.github/workflows/ci.yml
.gitignore
docs/infrastructure.md
scripts/heroku-build
scripts/heroku-exec

Resolves: <https://github.com/nextstrain/nextstrain.org/issues/850>
```
curl -n -X DELETE https://api.heroku.com/oauth/authorizations/6716fa11-cb1e-443a-be34-f9051cbb33b3 \
-H 'Accept: application/vnd.heroku+json; version=3'
```

Build, test, and deploy a Heroku slug instead of re-building on Heroku

---

scripts/heroku-build

The long options are from GNU coreutils, but macOS ships a BSD tty and du.  Only one of the swapped options is POSIX.
Noted by @joverlee521 in post-merge review.¹
¹ <https://github.com/nextstrain/nextstrain.org/pull/857#pullrequestreview-2053748042>

dev: Swap out a few long options for equivalent but more available short options

---

static-site/src/components/Footer/index.jsx
static-site/src/components/People/avatars.jsx
static-site/src/pages/team.jsx

No functional changes – prepping for #860

Update people component

---

.github/workflows/ci.yml
.github/workflows/index-resources.yml
aws/iam/policy/NextstrainDotOrgServerInstance-testing.tftpl.json
aws/iam/policy/NextstrainDotOrgServerInstance.tftpl.json
docs/resource-collection.rst
env/production/.terraform.lock.hcl
env/production/config.json
env/testing/.terraform.lock.hcl
env/testing/config.json
scripts/get-resource-index-ref-matrix
scripts/get-resource-index.js

This PR starts the use of versioned resource index JSONs so that we no longer run into out-of-sync issues between the canary and production servers. 
Major changes:
- the scheduled index resources workflow updates both canary and production resource index JSONs if they are different versions
- the CI workflow rebuilds the resource index before deployment of canary
- the CI workflow builds a `/tmp/<branch>` prefixed resource index for review apps
Related to https://github.com/nextstrain/nextstrain.org/issues/829
- ~[ ] Tick the wait for CI box in Heroku~

Separate indexer

---

.github/workflows/ci.yml

Follow up to #841 
Inherit secrets so that the called index-resource.yml workflow has access to repo secrets.

CI: fix use of index-resources.yml

---

.github/workflows/index-resources.yml
scripts/get-resource-index-ref-matrix

Working around the issue that `GITHUB_EVENT_NAME` points to the caller workflow context by using an input to flag the workflow_call event.
Workaround based on GitHub Actions discussion
<https://github.com/actions/runner/discussions/1884#discussioncomment-6377587>
Follow up to #841

index-resources.yml: Add `is-workflow-call` input

---

.gitignore
static-site/tsconfig.json

Configure TypeScript for static-site

---

static-site/src/components/Footer/index.jsx
static-site/src/components/Footer/sitemap.jsx
static-site/src/components/Footer/sitemap.yaml
static-site/src/components/splash/index.jsx

_[preview on contact page](https://nextstrain-s-victorlin--rytbno.herokuapp.com/contact)_
Adds links to the footer.
- #849

Add sitemap to footer

---

static-site/src/components/ListResources/Showcase.tsx

[_preview_](https://nextstrain-s-victorlin--ptoszr.herokuapp.com/pathogens)
Previously, the showcase would drop cards as the width decreases. This is presumably to prevent the showcase from taking up too much height. Instead of hiding the unused cards, allow them to be accessed by making the showcase expandable.
- Based on #874
- Prepping for #849
- Alternative to (closes #873)
- [Suggested](https://github.com/nextstrain/nextstrain.org/pull/873#issuecomment-2125430386) by @trvrb, [designed](https://github.com/nextstrain/nextstrain.org/pull/873#issuecomment-2125606373) by @tsibley

Make showcase expandable

---

static-site/vendored/react-scrollable-anchor/Manager.js
static-site/vendored/react-scrollable-anchor/index.js
static-site/vendored/react-scrollable-anchor/utils/hash.js

This (mainly `utils/hash.removeHash()`) modifies the current history entry which messes with browser navigation functions.
The handler's main purpose is to update the URL if the user scrolls to or away from an anchor, which isn't something that's necessary for our usage.
- Fixes #882

Remove scroll handler

---

static-site/src/components/ListResources/Showcase.tsx

#878 was approved but merged prematurely. Re-opening its contents to be merged after #874 (base) is merged

Make showcase expandable (re-open)

---

static-site/src/components/ListResources/IndividualResource.tsx

Resources that lack this attribute should at least have a width set based on displayName, not the fixed default of 200.
- Fixes #896

Move updateCadence check

---

static-site/src/components/ListResources/IndividualResource.tsx
static-site/src/components/ListResources/types.ts
static-site/src/components/ListResources/useDataFetch.ts

This attribute only served as an alias to determine if the optional attributes `firstUpdated|dates|nVersions|updateCadence` are available. It's more direct (and preferred by the compiler) to check for presence of the individual attributes directly where needed.
`versioned` at the top level on ListResourcesResponsiveProps is still valuable and should be kept.
- follow-up to https://github.com/nextstrain/nextstrain.org/pull/874#discussion_r1626764829

Remove `versioned` attribute from Resource interface

---

static-site/src/components/ListResources/IndividualResource.tsx

[_preview_](https://nextstrain-s-victorlin--kg9kva.herokuapp.com/pathogens)
- Use CSS hover selector instead of relying on a prop
- Limit the scope of ResourceLinkWrapper to just adding shift-click behavior
N/A, thought of this while working on #874

Simplify hover detection

---

scripts/heroku-build

Some things (Puppeteer during `npm` install, in some cases; `next build` when SWC deps are missing) want to store files in $HOME/.cache/ and that doesn't work due to permissions when HOME=/ (the fallback value provided by bash because it can't lookup a user for the uid we use).
I believe these caches are needed at build-time only and can be safely discarded afterwards.  If that turns out to not be the case, then we can switch to setting HOME=/build/app instead to include them in the slug.
Resolves: <https://github.com/nextstrain/nextstrain.org/issues/895>

scripts/heroku-build: Set HOME=/tmp for build

---

static-site/next.config.mjs

This avoids failure to create Heroku preview apps simply due to linting errors.
N/A
https://nextjs.org/docs/app/api-reference/next-config-js/eslint

Don't condition build status on lint result

---

static-site/src/components/ListResources/types.ts

The comment was inaccurate - PathVersions does not describe the exact response value of the API call but rather the the value of a nested key within the response.
The comment could be updated with that clarification, but it's also prone to becoming out of date (not always going to be from the /list-resources API call).
Thought of this while reviewing #904

Remove PathVersions comment

---

static-site/src/components/splash/index.jsx

[_preview_](https://nextstrain-s-victorlin--n9zj3t.herokuapp.com/)
Now that sections aren't required to have preview cards, a section for Nextclade without any cards can visually fit in.
- Based on #901
- #849
1. ~Where should the new Nextclade section be placed? I added it to the end but it should probably go elsewhere.~ [done](https://github.com/nextstrain/nextstrain.org/pull/902#discussion_r1632415779)
2. Does the description/button text look ok?

Add Nextclade section on splash

---

static-site/src/components/ListResources/IndividualResource.tsx
static-site/src/components/ListResources/ResourceGroup.tsx
static-site/src/components/ListResources/index.tsx
static-site/src/components/ListResources/types.ts
static-site/src/components/ListResources/useDataFetch.ts
static-site/src/pages/groups.jsx
static-site/src/sections/pathogens.jsx
static-site/src/sections/staging-page.jsx

Replaces the current "datasets" DatasetSelect component with a ListResources component that hits the same backend `charon` API. Also refactors in `useDataFetch` to change the hard-coded parser into a passed-in (mandatory) callback function, and updates two existing uses to the new pattern. Finally, adds in conditional display logic to the ListResources component to hide or otherwise not set UI elements that don't make sense with the `groups` dataset (e.g., last modified dates, since we don't have those). 
[Preview](https://nextstrain-s-group-reso-fafosr.herokuapp.com/groups)
#870

Replace Datasets DatasetSelect component on groups page with ListResources [#870]

---

static-site/src/components/ListResources/index.tsx
static-site/src/components/ListResources/types.ts
static-site/src/components/ListResources/useDataFetch.ts

Small improvements suggested by others.
Follow-up to:
- #874
- https://github.com/nextstrain/nextstrain.org/pull/901#discussion_r1632403960
- [Slack thread](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1718253665526349)

Update usage of TypeScript

---

data/manifest_core.json

See https://github.com/nextstrain/mpox/pull/254 for context on the dataset itself.
The [dataset itself is live](https://nextstrain.org/mpox/clade-I) (via [this action run](https://github.com/nextstrain/mpox/actions/runs/9606998203/job/26497445439)), this PR just adds it to the sidebar dropdown in Auspice.

Add mpox/clade-I to manifest

---

static-site/src/components/splash/index.jsx
static-site/src/components/splash/styles.jsx

[_preview_](https://nextstrain-s-victorlin--3pu27z.herokuapp.com)
Styling fixes as a follow-up to #901 + #902
#849

Splash page styling fixes

---

static-site/content/resource-listing.yaml
static-site/src/components/ListResources/index.tsx
static-site/src/components/Showcase/index.tsx
static-site/src/components/splash/index.jsx

_[preview](https://nextstrain-s-victorlin--7dxrsz.herokuapp.com/)_
Small fixes - see commit messages.
- Prepping for #922
- Resolves https://github.com/nextstrain/nextstrain.org/pull/878#discussion_r1617752924
- Closes https://github.com/nextstrain/nextstrain.org/issues/883

Showcase refactor and additions

---

static-site/src/components/Groups/Tiles/index.tsx
static-site/src/components/Groups/Tiles/styles.tsx
static-site/src/pages/groups.jsx

[_preview_](https://nextstrain-s-victorlin--rgwhw6.herokuapp.com/groups)
ExpandableTiles is already used in two other places where tiles are used. Use it here too for consistency.
https://github.com/nextstrain/nextstrain.org/issues/947

Make group tiles expandable

---

.github/workflows/ci.yml

The concurrency limit on the deploy step was meant to prevent multiple deployment processes from running at the same time. However, most of the time spent on the deployment process is in the build step, which means there is not likely to be any overlap on the deploy step.
Set the limit on the workflow level to capture the entire deployment process. This will also affect runs that don't deploy (e.g. PR updates), but most of the time only the latest push to a PR is important so it's fine that older runs are canceled.
Closes #935

Move concurrency limit to the workflow level

---

data/manifest_core.json

Add different time resolution to the RSV builds to produce the hierarchy (defaults in italics):
- a
- *genome*
- all-time
- *6y*
- 3y
- F
- all-time
- *6y*
- 3y
- G 
- all-time
- *6y*
- 3y
- b
- *genome*
- all-time
- *6y*
- 3y
- F
- all-time
- *6y*
- 3y
- G 
- all-time
- *6y*
- 3y

manifest: update rsv resolutions

---

data/manifest_core.json

See <https://github.com/nextstrain/avian-flu/pull/69> and <https://github.com/nextstrain/avian-flu/pull/72> for details of the new datasets themselves.
Segments ordered following the other avian-flu builds in the manifest, although note that this order differs from the canonical order of "pb2", "pb1", "pa", "ha","np", "na", "mp", "ns" which is used to order segments in the avian-flu/h5n1-cattle-outbreak/genome build.

Update manifest with h5n1-cattle-outbreak segments

---

static-site/src/components/Datasets/situation-reports-by-language.jsx
static-site/src/components/Footer/index.jsx
static-site/src/components/Footer/sitemap.jsx
static-site/src/components/logos.jsx
static-site/src/components/nav-bar/index.jsx
static-site/src/components/splash/index.jsx
static-site/src/components/splash/styles.jsx
static-site/src/layouts/generalComponents.jsx
static-site/src/layouts/generic-page.jsx
static-site/src/sections/sars-cov-2-page.jsx
static-site/src/styles/bootstrap.css

_[preview](https://nextstrain-s-victorlin--ywrpjq.herokuapp.com/)_
_below is from the main commit, but there are additional smaller commits_
It's not clear to me where this bootstrap.css file came from, but it seems to be roughly a small subset of the bootstrap.css file distributed¹ in v3.4.1. This commit replaces it with the bootstrap-grid.css file distributed in v4.6.2.
Bootstrap v4 introduced more precise breakpoints and shifted the xs/sm/md/lg classes one level down from the previous version.² Usage has been adjusted accordingly.
¹ https://getbootstrap.com/docs/3.4/getting-started/#download
² https://getbootstrap.com/docs/4.0/migration/#responsive-utilities

Update to Bootstrap v4

---

static-site/.eslintrc.yaml
static-site/src/components/Groups/Tiles/index.tsx
static-site/src/components/ListResources/index.tsx
static-site/src/components/People/avatars.jsx
static-site/src/components/logos.jsx
static-site/src/components/splash/index.tsx
static-site/src/sections/sars-cov-2-forecasts-page.jsx

The pattern of using require("path/to/image").default.src is project-wide rather than individual one-offs. In this case, it makes more sense to disable the rule across the project in files which may import images.
Closes #959

Allow require() outside of import statements

---

static-site/src/components/Footer/sitemap.jsx

Fixes a styling issue noted by @tsibley [on Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1722362495986289?thread_ts=1722357213.513769&cid=C01LCTT7JNN) and another that I noticed upon closer inspection.

Tweak footer styles

---

static-site/src/components/nav-bar/index.tsx
static-site/src/templates/displayMarkdown.jsx

Follow-up to #958 which caused regressions on blog pages. Noted by @trvrb [on Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1722453675360609).

Fix styles for blog pages

---

static-site/src/components/Groups/Tiles/index.tsx

_[preview](https://nextstrain-s-victorlin--3ajzg9.herokuapp.com/groups)_
There's no good reason to keep the order from the groups.json file and I can't imagine any users finding that order useful. Alphabetical could make it easier to find and see related groups (e.g. public/private pairs that share a prefix).
Closes #953

Sort group tiles alphabetically

---

.github/workflows/ci.yml

Reasoning in added comment.
Workaround for #975

Temporarily bypass broken resource indexer

---

env/production/config.json
env/testing/config.json
resourceIndexer/inventory.js

This is necessary for the core collection inventory which is now split into 2 files.
- #975

Support multiple inventory files

---

resourceIndexer/inventory.js

Follow-up to "Derive inventory path from key in manifest" (4b2257cb).
Caught by @jameshadfield in review: https://github.com/nextstrain/nextstrain.org/pull/979#discussion_r1713066094
- There is a change in `resourceIndexer/*` however it is a non-functional change which shouldn't require version bump.

Fix _localInventoryPath JSDoc

---

package-lock.json
package.json
src/endpoints/sources.js
src/sources/models.js

Useful for downloads not via `nextstrain remote download` that still want to use our conventional file naming.
For example, with curl:
curl https://nextstrain.org/avian-flu/h5n1/ha/all-time \
--header 'Accept: application/vnd.nextstrain.dataset.main+json' \
--remote-name --remote-header-name
curl https://nextstrain.org/groups/blab/ncov/wa/2m \
--header 'Accept: application/vnd.nextstrain.dataset.main+json' \
--remote-name --remote-header-name
and wget:
wget https://nextstrain.org/avian-flu/h5n1/ha/all-time \
--header 'Accept: application/vnd.nextstrain.dataset.main+json' \
--content-disposition
wget https://nextstrain.org/groups/blab/ncov/wa/2m \
--header 'Accept: application/vnd.nextstrain.dataset.main+json' \
--content-disposition
the filenames will be:
avian-flu_h5n1_ha_all-time.json …

Send Content-Disposition header with our conventional filename in RESTful API responses

---

.github/workflows/ci.yml
scripts/heroku-build
scripts/heroku-exec

The Heroku-20 stack is deprecated and we have been bombarded with warnings and messages from Heroku telling us to upgrade.
<https://help.heroku.com/NPN275RK/heroku-20-end-of-life-faq>
- #974

Use Heroku-22 stack

---

.github/workflows/ci.yml
.github/workflows/index-resources.yml
docs/resource-collection.rst
scripts/check-resource-index-match.js

Ensures that the index-resource workflow always uses the production config as our Heroku apps default to NODE_ENV=production.¹
¹ <https://docs.nextstrain.org/projects/nextstrain-dot-org/en/latest/infrastructure.html#environment-or-config-variables>
Resolves https://github.com/nextstrain/nextstrain.org/issues/980

Always use production config.json in index-resources GH Action

---

src/endpoints/groups.js
src/groups.js
src/routing/groups.js
static-site/pages/groups/[...groupName].jsx
static-site/src/layouts/generic-page.jsx
static-site/src/pages/contact.jsx
static-site/src/pages/groups.jsx
static-site/src/pages/index.jsx
static-site/src/pages/team.jsx
static-site/src/sections/community-page.jsx
static-site/src/sections/community-repo-page.jsx
static-site/src/sections/group-members-page.tsx
static-site/src/sections/group-settings-page.jsx
static-site/src/sections/individual-group-page.jsx
static-site/src/sections/pathogens.jsx
static-site/src/sections/sars-cov-2-forecasts-page.jsx
static-site/src/sections/sars-cov-2-page.jsx
static-site/src/sections/staging-page.jsx
static-site/src/templates/displayMarkdown.jsx

The new page is available at `groups/<groupName>/settings/members`. I chose to use the same URL as the API so that we don't have to take up another namespace (e.g. `groups/<groupName>/members`). The main Group page will only link out to the members page if the current user is authorized to list Group members.
The members list only displays the most privileged role for each member to keep the display simple. It assumes the group roles API returns the roles in the order from least to most privileged.
The plan is to make future changes to this page to allow Group owners to edit members here as well. I'm making that a separate change to keep this PR simple. 
Related to #804

Add page for listing Group members 

---

static-site/src/sections/group-members-page.tsx

I didn't realize that `toSorted` is a relatively new method that is not supported in older browser versions.¹
Thanks to @tsibley for using an old version of FireFox and catching this.
¹ <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted#browser_compatibility>
Follow up to https://github.com/nextstrain/nextstrain.org/pull/973

group-members-page: Replace `toSorted()` with shallow copy + `sort()`

---

static-site/content/featured-analyses.yaml
static-site/src/components/splash/index.tsx

Previously, the code assumed that all URLs started with `/` and was noted in featured-analyses.yaml. However, there was nothing to check this. A `/` is perfectly valid for everything except for the source check, which silently assumes everything that doesn't start with `/` is maintained by Nextstrain. This is a bad assumption.
The source check could either (1) be updated to work with the error or (2) throw a runtime error. I chose to go with (1) to make things easier when updating featured analyses.
Follow-up to https://github.com/nextstrain/nextstrain.org/pull/993#discussion_r1729422975

Auto-prepend `/` to tile URLs

---

static-site/content/blog/2018-05-14-new-nextstrain-website.md
static-site/content/blog/2019-10-21-auspice-v2.md
static-site/content/blog/2019-10-31-using-narratives-to-explain-west-nile-virus-spread.md
static-site/content/blog/2020-06-02-SARSCoV2-clade-naming.md
static-site/content/blog/2021-01-06-updated-SARS-CoV-2-clade-naming.md
static-site/content/blog/2021-07-08-ncov-open-announcement.md
static-site/content/blog/2022-04-29-SARS-CoV-2-clade-naming-2022.md
static-site/content/blog/2024-03-27-annual-update-march-2024.md
static-site/content/blog/2024-06-12-new-resources-for-measles.md
static-site/content/blog/2024-06-18-h5n1-cattle-outbreak-analysis-and-resources.md
static-site/content/blog/2024-09-03-augur-v25-features.md
static-site/pages/blog.jsx
static-site/pages/blog/[id].jsx
static-site/src/components/Sidebar/index.jsx
static-site/src/util/blogPosts.js

[Preview](https://nextstrain-s-sidebar-ti-iwuz4n.herokuapp.com/blog/)
Add support for explicit, optional `sidebarTitle` key in blog post frontmatter 
* Removes previous calculated `sidebarName` post object key in favor of optional `sidebarTitle` in post frontmatter
* If frontmatter does not contain `sidebarTitle`, `post.sidebarTitle` is set tot the frontmatter `title` value
* Update blog JSX files to use `post.sidebarTitle` instead of `post.sidebarName`
* Delete now unused `formatFileName()` method
* Add `sidebarTitle` frontmatter values as needed to (mostly) replicate the current sidebar titles (formerly based on the post file name)
* Correct some trailing whitespace
Closes #1005

Add support for `sidebarTitle` value in blog post frontmatter; fix existing blog sidebar titles [#1005]

---

package-lock.json
package.json
static-site/pages/_document.tsx
static-site/src/components/SEO/SEO.jsx
static-site/src/components/layout.jsx
static-site/src/layouts/generic-page.jsx
static-site/src/pages/404.jsx
static-site/src/pages/index.jsx
static-site/src/templates/displayMarkdown.jsx

* Switch from using `react-helmet` to `next/head` for populating `<head>` element in pages
* Swap various `<Helmet>` usage to `<Head>`
* Migrate social media-related metadata headers to `_document.tsx`
This is a preliminary step that fixes feed auto-discovery; subsequent work will get full metadata headers (i.e., OpenGraph, etc) into un-hydrated renders.
Closes #1011

Fix (some) header metadata generation in un-hydrated content [#1011]

---

static-site/src/components/ExpandableTiles/index.tsx

In all current usages of ExpandableTiles, it is possible for and sometimes even expected for users to interact with tiles by clicking. Having an invisible overlay on top of the last row of tiles with a separate onClick behavior can be confusing for users expecting another onClick behavior.
When the tiles are expanded, the only benefit to having PreviewOverlay available is for the onClick behavior of hiding the tiles. This can already be accomplished by the ArrowButton which also covers full width and has a height of 1em.
This removes the opacity transition, which in my eyes does not make a noticeable difference. The visually distinct part of the transition action is on the height change to show more rows of tiles, not the opacity here.
Closes #1010

Remove PreviewOverlay when expanded

---

static-site/src/components/ListResources/index.tsx
static-site/src/components/ListResources/types.ts
static-site/src/components/ListResources/useFilterOptions.ts
static-site/src/components/ListResources/useSortAndFilter.ts

With this PR, all files under [static-site/src/components/ListResources](https://github.com/nextstrain/nextstrain.org/blob/5d85bd9d18b175c0d7a304960eccbce53e411f82/static-site/src/components/ListResources/) (with the exception of vendored `dodge.js`) are TypeScript files.
- #871
- Follow-up to #874
- Prompted by thinking around https://github.com/nextstrain/nextstrain.org/pull/1035

Finish adding types to ListResources

---

build.sh

Auspice's prepare script builds Auspice and by default will run during installation. It is not necessary here since there is a custom build call right after installation.
Notably, this avoids [installation of devDependencies for git installs](https://docs.npmjs.com/cli/v10/using-npm/scripts#life-cycle-scripts). One of the devDependencies, puppeteer, has recently been timing out on Heroku in attempts to download Chrome.
- https://github.com/nextstrain/auspice/issues/1709

auspice-client: Speed up build

---

static-site/content/blog/2024-10-22-oropouche-analysis-and-resources.md

Fixing links to the fasta files and metadata.tsv on the oropouche blogpost

fixing links for seq and metadata files

---

static-site/src/components/ExpandableTiles/index.tsx
static-site/src/components/ListResources/IndividualResource.tsx
static-site/src/components/ListResources/Modal.tsx
static-site/src/components/ListResources/ResourceGroup.tsx
static-site/src/components/ListResources/index.tsx
static-site/src/components/ListResources/useDataFetch.ts

Reformatting for consistency with files in Auspice codebase
- https://github.com/nextstrain/auspice/issues/1890

Reformat TypeScript files

---

static-site/src/components/ListResources/index.tsx

For consistency. If there was an ESLint rule for consistency within the same line, I would consider turning it on. But I don't think such a rule exists. The closest is [jsx-quotes](https://eslint.org/docs/latest/rules/jsx-quotes) which is too opinionated and would change lots of code that is working just fine.
Prompted by https://github.com/nextstrain/nextstrain.org/pull/1073#discussion_r1842669224

(nit) Use double quotes in the same line

---

static-site/src/components/ListResources/IndividualResource.tsx
static-site/src/components/ListResources/Modal.tsx
static-site/src/components/ListResources/ResourceGroup.tsx
static-site/src/components/ListResources/errors.tsx
static-site/src/components/ListResources/index.tsx
static-site/src/components/ListResources/types.ts
static-site/src/components/ListResources/useDataFetch.ts
static-site/src/components/ListResources/useSortAndFilter.ts

I mainly went through 54be4d60c17e62d236ad95d10aff3895ca0a4553 and looked for things that can be improved. See commit messages for details.
- Closes #892

Improve type narrowing and error handling

---

static-site/.eslintrc.yaml
static-site/app/blog/[id]/page.tsx
static-site/src/components/ErrorBoundary.tsx
static-site/src/components/Groups/Tiles/index.tsx
static-site/src/components/ListResources/IndividualResource.tsx
static-site/src/components/ListResources/Modal.tsx
static-site/src/components/ListResources/ResourceGroup.tsx
static-site/src/components/ListResources/index.tsx
static-site/src/components/ListResources/types.ts
static-site/src/components/ListResources/useDataFetch.ts
static-site/src/components/splash/index.tsx
static-site/src/sections/group-members-page.tsx

While working on #1073, I thought it was reasonable to avoid casting and non-null assertions across the entire codebase. This is an attempt to enforce it and address outstanding violations.
Follow-up to https://github.com/nextstrain/nextstrain.org/pull/1073#discussion_r1843065163

Stricter types

---

.github/workflows/ci.yml
package.json
static-site/types.d.ts

Previously, the only enforcement of TypeScript was through ESLint rules from @typescript-eslint.
- Closes #1072
- Closes #1080

Check types in CI

---

static-site/components/nav/nav-logo.tsx

This is not reflected in the type definition for Next.js's Image element, but width and height [must be set together](https://nextjs.org/docs/app/building-your-application/optimizing/images#image-sizing).
Follow-up to https://github.com/nextstrain/nextstrain.org/issues/1072#issuecomment-2489442505

Add height property to Next.js Image

---

static-site/app/blog/parseMarkdown.ts
static-site/app/blog/utils.ts
static-site/app/styles/globals.css

_[preview](https://nextstrain-s-victorlin--45xpgm.herokuapp.com/blog/2024-12-10-auspice-2024)_
This PR adds [GitHub-style anchor links](https://github.com/markedjs/marked/blob/10020d018d4448b1d2d4612baf650c4e3a5949bf/docs/USING_PRO.md#the-renderer--renderer) to heading elements. I also added a '#' on hover. Styles added in globals.css. Not ideal since it is also added to non-blog pages, but this was the easiest thing to do in absence of a blog-specific static CSS f
N/A, thought of this while working on #1089

blog: Add anchor links to headings

---

data/manifest_core.json
env/production/config.json
env/testing/config.json
src/routing/core.js

Also bumps resource index revision number in testing and production configs.
Note: needs to merge semi-concurrently with the work for nextstrain/yellow-fever#25.

Add yellow-fever to manifest

---

static-site/src/components/sourceInfoHeading.jsx

The purpose of the scaling is unclear. It was added in "parse /groups/:groupName markdown;" (347ee033) which is the commit that added the markdown rendering of group descriptions, so maybe it was a stylistic adjustment relative to whatever else was on the page at that time.
A similar 94% font-size scaling is used in the custom Auspice splash page (auspice-client/customisations/splash.js) as well as other parts of the Auspice code base. The purposes of those are also unclear.
The main motivation for removing it here is that there was an [internal bug report](https://bedfordlab.slack.com/archives/C0K3GS3J8/p1731343211138099) of a group's description rendering with what looks like partially scaled fonts. The issue self-resolved without any code changes and we were unable to understand what …

Remove font-size scaling

---

.github/workflows/ci.yml
.github/workflows/dependabot-automation.yml
.github/workflows/index-resources.yml
.github/workflows/remind-to-promote.yml
.github/workflows/terraform-lint.yml

Bump all GH Action workflows to `ubuntu-24.04` and address breakages.
1. Added installation steps for Terraform
2. We interact with Heroku via the Platform API so we are not affected by the removal of the Heroku CLI.
Related to https://github.com/nextstrain/.github/issues/113

Bump GH Action workflows to `ubuntu-24.04`

---

static-site/content/blog/2025-01-09-human-metapneumovirus-analysis-and-resources.md

The date in the file name and front matter was last updated on 2024-01-07, however it is now 2024-01-09 and the post hasn't been published to nextstrain.org yet. Updated the date to today, and will promote to nextstrain.org after merge.
Follow-up to #1101

Update blog post date

---

docs/redis.rst

Update Redis docs

---

auspice-client/customisations/languageSelector.js
auspice-client/customisations/navbar.js
auspice-client/customisations/splash.js

This reverts commit "auspice-client: Append extension on ESM imports" (7cde8399).
The reasoning in that commit was that extensions are necessary for Webpack 5. However, this is not entirely accurate - they are only [required](https://webpack.js.org/configuration/module/#resolvefullyspecified) when using the default for resolve.fullySpecified *and* using "type": "module" package.json. The latter is not true in our case.
Notably, removing the exact path for `auspice/src/components/markdownDisplay` allows the usage to be tolerant of filename changes such as TypeScript conversion.
Unblocks changes such as https://github.com/nextstrain/auspice/commit/ff91cfd17a16063a6890b65d8a23c929297c3fc8
- This confirms navbar and languageSelector changes
- This confirms splash changes

Remove extension on ESM imports

---

data/manifest_core.json

Build PR: https://github.com/nextstrain/avian-flu/pull/126
Preview URL: https://nextstrain-s-james-avia-qlfqbu.herokuapp.com/avian-flu/h5n1-d1.1/genome
I didn't add this to the featured datasets list at this stage, but we can if people think it's warranted

Add avian-flu/h5n1-d1.1/genome core build

---

.eslintrc.yaml

Developers should be free to choose whatever linebreak style they wish.
<https://eslint.org/docs/latest/rules/operator-linebreak>
Follow-up to https://github.com/nextstrain/nextstrain.org/pull/1076#discussion_r1842762650
N/A

eslint: Remove enforcement of operator-linebreak

---

data/manifest_core.json
test/date_descriptor.test.js
test/inventory_parsing.test.js

Renamed the default "wnv/global" to "wnv/all-lineages" and updated the tests accordingly.
This PR should come after related WNV PR:
* https://github.com/nextstrain/WNV/pull/88

Rename "wnv/global" to "wnv/all-lineages"

---

data/manifest_core.json

Part of migration of WA WNV trees to NW-PaGe

Migrate WA tree from WNV list to NW-PaGe

---

src/redirects.js

Workshop attendees will be typing a URL into their browser as the first step. 'https://nextstrain.org/workshop' is easier to type than 'https://github.com/nextstrain/nextstrain-walkthrough', plus it looks nicer.

Add /workshop redirect link

---

static-site/content/blog/2025-04-22-conda-runtime-out-of-sync-issue.md

[Test app preview](https://nextstrain-s-add-blog-c-tftw8e.herokuapp.com/blog/2025-04-22-conda-runtime-out-of-sync-issue)
https://github.com/nextstrain/conda-base/issues/105

Add blog post on Conda runtime issue

---

logo/README.md

The non-portable version can render differently on various browsers. For me, the font appears much thinner than the portable version.
Before and after:

Use portable version of logo in README

---

data/manifest_core.json

Update mumps resolution names and default view after https://github.com/nextstrain/mumps/pull/22 is merged
* Change mump resolution name from "na" to "north-america"
* Do not redirect from "mumps/na" to "mumps/north-america" since "mumps/na" is still being used by the narrative tutorial and is related to a recent paper
* https://github.com/nextstrain/mumps/issues/19#issuecomment-2831224800
* Change default view of mumps from "north-america" to "global"

Update mumps resolution names and default view

---

src/endpoints/cli.js
src/routing/cli.js

Nextstrain CLI will soon start querying this endpoint for its own update check instead of querying PyPI directly.  This gives us insights into usage and also more flexibility to shift how we're releasing and distributing it.
Related-to: <https://github.com/nextstrain/cli/pull/434>

endpoints/cli: Provide the latest CLI version as JSON on the /cli endpoint

---

static-site/components/plausible-analytics/index.tsx
static-site/data/BaseConfig.js
static-site/pages/_app.tsx

Adds config values to BaseConfig for script URL and `data-domain` prop. Setting the config values to `undefined` will disable inclusion of the analytics script completely.
Closes #1162

Make use of Plausible Analytics configurable [#1162]

---

env/production/config.json
package-lock.json
package.json
src/analytics.js
src/config.js
src/routing/cli.js
src/routing/pathogenRepos.js

These will help us in the future gain insight into Nextstrain CLI version usage and update patterns as well as pathogen repository setup and update patterns.

Record Plausible analytics events for endpoints intended for Nextstrain CLI
